/* GL 3.3 pixel-store GPU/host layout oracle. */
#include <dlfcn.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <EGL/egl.h>
#include <GL/glcorearb.h>
static int checks=0,failures=0;
#define CHECK(c,fmt,...) do{++checks;if(c)printf("ok  : " fmt "\n",##__VA_ARGS__);else{printf("FAIL: " fmt "\n",##__VA_ARGS__);++failures;}}while(0)
typedef struct A{const GLubyte*(*GetString)(GLenum);GLenum(*GetError)(void);void(*Finish)(void);void(*PixelStorei)(GLenum,GLint);void(*GenTextures)(GLsizei,GLuint*);void(*BindTexture)(GLenum,GLuint);void(*TexParameteri)(GLenum,GLenum,GLint);void(*TexImage2D)(GLenum,GLint,GLint,GLsizei,GLsizei,GLint,GLenum,GLenum,const void*);void(*GenFramebuffers)(GLsizei,GLuint*);void(*BindFramebuffer)(GLenum,GLuint);void(*FramebufferTexture2D)(GLenum,GLenum,GLenum,GLuint,GLint);GLenum(*CheckFramebufferStatus)(GLenum);void(*ReadPixels)(GLint,GLint,GLsizei,GLsizei,GLenum,GLenum,void*);}A;
#define L(a,h,f) do{(a)->f=(__typeof__((a)->f))dlsym((h),"gl"#f);CHECK((a)->f!=NULL,"resolve gl%s",#f);}while(0)
static int load(void*h,A*a){memset(a,0,sizeof(*a));L(a,h,GetString);L(a,h,GetError);L(a,h,Finish);L(a,h,PixelStorei);L(a,h,GenTextures);L(a,h,BindTexture);L(a,h,TexParameteri);L(a,h,TexImage2D);L(a,h,GenFramebuffers);L(a,h,BindFramebuffer);L(a,h,FramebufferTexture2D);L(a,h,CheckFramebufferStatus);L(a,h,ReadPixels);return failures==0;}
#undef L
static int egl(void*h){EGLDisplay(*gd)(EGLNativeDisplayType)=dlsym(h,"eglGetDisplay");EGLBoolean(*init)(EGLDisplay,EGLint*,EGLint*)=dlsym(h,"eglInitialize");EGLBoolean(*ba)(EGLenum)=dlsym(h,"eglBindAPI");EGLBoolean(*gc)(EGLDisplay,EGLConfig*,EGLint,EGLint*)=dlsym(h,"eglGetConfigs");EGLContext(*cc)(EGLDisplay,EGLConfig,EGLContext,const EGLint*)=dlsym(h,"eglCreateContext");EGLSurface(*ps)(EGLDisplay,EGLConfig,const EGLint*)=dlsym(h,"eglCreatePbufferSurface");EGLBoolean(*mc)(EGLDisplay,EGLSurface,EGLSurface,EGLContext)=dlsym(h,"eglMakeCurrent");CHECK(gd&&init&&ba&&gc&&cc&&ps&&mc,"resolve EGL");if(!gd||!init||!ba||!gc||!cc||!ps||!mc)return 0;EGLDisplay d=gd(EGL_DEFAULT_DISPLAY);EGLint x=0,y=0;CHECK(d!=EGL_NO_DISPLAY&&init(d,&x,&y),"init EGL");CHECK(ba(EGL_OPENGL_API),"bind API");EGLConfig c=0;EGLint n=0;CHECK(gc(d,&c,1,&n)&&n>0,"config");const EGLint ca[]={EGL_CONTEXT_MAJOR_VERSION,3,EGL_CONTEXT_MINOR_VERSION,3,EGL_NONE},pa[]={EGL_WIDTH,8,EGL_HEIGHT,8,EGL_NONE};EGLContext cx=cc(d,c,EGL_NO_CONTEXT,ca);EGLSurface s=ps(d,c,pa);CHECK(cx!=EGL_NO_CONTEXT&&s!=EGL_NO_SURFACE,"context/pbuffer");CHECK(mc(d,s,s,cx),"make current");return cx!=EGL_NO_CONTEXT&&s!=EGL_NO_SURFACE;}
static void setpx(uint8_t*b,int row,int col,uint8_t r,uint8_t g,uint8_t bl){size_t o=(size_t)(row*4+col)*4;b[o]=r;b[o+1]=g;b[o+2]=bl;b[o+3]=255;}
static int eq4(const uint8_t*p,int r,int g,int b){return p[0]==r&&p[1]==g&&p[2]==b&&p[3]==255;}
static int sentinel_except(const uint8_t*b,size_t n,size_t a0,size_t a1,size_t b0,size_t b1){for(size_t i=0;i<n;i++){int in=(i>=a0&&i<a1)||(i>=b0&&i<b1);if(!in&&b[i]!=0xCD)return 0;}return 1;}
int main(int ac,char**av){const char*path=ac>1?av[1]:"./libmithril.dylib";void*h=dlopen(path,RTLD_NOW|RTLD_GLOBAL);CHECK(h!=0,"dlopen %s",path);if(!h)return 2;if(!egl(h))return 2;A a;if(!load(h,&a))return 2;const char*v=(const char*)a.GetString(GL_VERSION);CHECK(v&&strstr(v,"3.3.0")&&strstr(v,"DirectMetal"),"DirectMetal 3.3 active (%s)",v?v:"null");while(a.GetError()!=GL_NO_ERROR){}
 uint8_t src[64];memset(src,0x7B,sizeof(src));setpx(src,1,1,255,0,0);setpx(src,1,2,0,255,0);setpx(src,2,1,0,0,255);setpx(src,2,2,255,255,0);
 a.PixelStorei(GL_UNPACK_ALIGNMENT,8);a.PixelStorei(GL_UNPACK_ROW_LENGTH,4);a.PixelStorei(GL_UNPACK_SKIP_ROWS,1);a.PixelStorei(GL_UNPACK_SKIP_PIXELS,1);GLuint t=0;a.GenTextures(1,&t);a.BindTexture(GL_TEXTURE_2D,t);a.TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST);a.TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST);a.TexImage2D(GL_TEXTURE_2D,0,GL_RGBA8,2,2,0,GL_RGBA,GL_UNSIGNED_BYTE,src);a.PixelStorei(GL_UNPACK_ALIGNMENT,4);a.PixelStorei(GL_UNPACK_ROW_LENGTH,0);a.PixelStorei(GL_UNPACK_SKIP_ROWS,0);a.PixelStorei(GL_UNPACK_SKIP_PIXELS,0);
 GLuint f=0;a.GenFramebuffers(1,&f);a.BindFramebuffer(GL_FRAMEBUFFER,f);a.FramebufferTexture2D(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_TEXTURE_2D,t,0);CHECK(a.CheckFramebufferStatus(GL_FRAMEBUFFER)==GL_FRAMEBUFFER_COMPLETE,"FBO complete");uint8_t p[4];a.Finish();a.ReadPixels(0,0,1,1,GL_RGBA,GL_UNSIGNED_BYTE,p);CHECK(eq4(p,255,0,0),"unpack row0 col0 = red (%u,%u,%u,%u)",p[0],p[1],p[2],p[3]);a.ReadPixels(1,0,1,1,GL_RGBA,GL_UNSIGNED_BYTE,p);CHECK(eq4(p,0,255,0),"unpack row0 col1 = green (%u,%u,%u,%u)",p[0],p[1],p[2],p[3]);a.ReadPixels(0,1,1,1,GL_RGBA,GL_UNSIGNED_BYTE,p);CHECK(eq4(p,0,0,255),"unpack row1 col0 = blue (%u,%u,%u,%u)",p[0],p[1],p[2],p[3]);a.ReadPixels(1,1,1,1,GL_RGBA,GL_UNSIGNED_BYTE,p);CHECK(eq4(p,255,255,0),"unpack row1 col1 = yellow (%u,%u,%u,%u)",p[0],p[1],p[2],p[3]);
 uint8_t dst[64];memset(dst,0xCD,sizeof(dst));a.PixelStorei(GL_PACK_ALIGNMENT,8);a.PixelStorei(GL_PACK_ROW_LENGTH,4);a.PixelStorei(GL_PACK_SKIP_ROWS,1);a.PixelStorei(GL_PACK_SKIP_PIXELS,1);a.ReadPixels(0,0,2,2,GL_RGBA,GL_UNSIGNED_BYTE,dst);a.Finish();CHECK(eq4(dst+20,255,0,0),"pack row1 col1 = red");CHECK(eq4(dst+24,0,255,0),"pack row1 col2 = green");CHECK(eq4(dst+36,0,0,255),"pack row2 col1 = blue");CHECK(eq4(dst+40,255,255,0),"pack row2 col2 = yellow");CHECK(sentinel_except(dst,sizeof(dst),20,28,36,44),"pack skips/padding remain untouched");a.PixelStorei(GL_PACK_ALIGNMENT,4);a.PixelStorei(GL_PACK_ROW_LENGTH,0);a.PixelStorei(GL_PACK_SKIP_ROWS,0);a.PixelStorei(GL_PACK_SKIP_PIXELS,0);CHECK(a.GetError()==GL_NO_ERROR,"pixel-store oracle ends without GL error");printf("PIXEL STORE SEMANTICS SMOKE: %d checks, %d failure(s)\n",checks,failures);if(!failures)printf("PIXEL STORE SEMANTICS SMOKE ALL PASSED\n");return failures?1:0;}
