/* OpenGL vs Metal primitive-restart boundary oracle.
 * OpenGL treats max-valued indices as ordinary vertices when restart is
 * disabled. Metal documents max U16/U32 as restart sentinels. Triangle lists
 * do not expose the difference reliably on current Apple GPUs, so this uses a
 * triangle strip where treating 0xffff as a sentinel removes the only visible
 * triangle. U8 is included because DirectMetal widens it to U16 and therefore
 * must preserve 0xff as an ordinary index when restart is disabled.
 */
#include <dlfcn.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <EGL/egl.h>
#include <GL/glcorearb.h>
#ifndef GL_PRIMITIVE_RESTART_FIXED_INDEX
#define GL_PRIMITIVE_RESTART_FIXED_INDEX 0x8D69
#endif
#define W 128
#define H 96
static int checks,failures;
#define CHECK(c,fmt,...) do{++checks;if(c)printf("ok  : " fmt "\n",##__VA_ARGS__);else{printf("FAIL: " fmt "\n",##__VA_ARGS__);++failures;}}while(0)
typedef struct A{void(*Disable)(GLenum);void(*Viewport)(GLint,GLint,GLsizei,GLsizei);void(*ClearColor)(GLfloat,GLfloat,GLfloat,GLfloat);void(*Clear)(GLbitfield);void(*Finish)(void);void(*ReadPixels)(GLint,GLint,GLsizei,GLsizei,GLenum,GLenum,void*);void(*GenTextures)(GLsizei,GLuint*);void(*BindTexture)(GLenum,GLuint);void(*TexParameteri)(GLenum,GLenum,GLint);void(*TexImage2D)(GLenum,GLint,GLint,GLsizei,GLsizei,GLint,GLenum,GLenum,const void*);void(*GenFramebuffers)(GLsizei,GLuint*);void(*BindFramebuffer)(GLenum,GLuint);void(*FramebufferTexture2D)(GLenum,GLenum,GLenum,GLuint,GLint);GLenum(*CheckFramebufferStatus)(GLenum);GLuint(*CreateShader)(GLenum);void(*ShaderSource)(GLuint,GLsizei,const GLchar*const*,const GLint*);void(*CompileShader)(GLuint);void(*GetShaderiv)(GLuint,GLenum,GLint*);GLuint(*CreateProgram)(void);void(*AttachShader)(GLuint,GLuint);void(*LinkProgram)(GLuint);void(*GetProgramiv)(GLuint,GLenum,GLint*);void(*UseProgram)(GLuint);void(*GenVertexArrays)(GLsizei,GLuint*);void(*BindVertexArray)(GLuint);void(*GenBuffers)(GLsizei,GLuint*);void(*BindBuffer)(GLenum,GLuint);void(*BufferData)(GLenum,GLsizeiptr,const void*,GLenum);void(*VertexAttribPointer)(GLuint,GLint,GLenum,GLboolean,GLsizei,const void*);void(*EnableVertexAttribArray)(GLuint);void(*DrawElements)(GLenum,GLsizei,GLenum,const void*);GLenum(*GetError)(void);}A;
#define L(a,h,f) do{(a)->f=(__typeof__((a)->f))dlsym(h,"gl"#f);CHECK((a)->f,"resolve gl%s",#f);}while(0)
static void load(void*h,A*a){memset(a,0,sizeof(*a));L(a,h,Disable);L(a,h,Viewport);L(a,h,ClearColor);L(a,h,Clear);L(a,h,Finish);L(a,h,ReadPixels);L(a,h,GenTextures);L(a,h,BindTexture);L(a,h,TexParameteri);L(a,h,TexImage2D);L(a,h,GenFramebuffers);L(a,h,BindFramebuffer);L(a,h,FramebufferTexture2D);L(a,h,CheckFramebufferStatus);L(a,h,CreateShader);L(a,h,ShaderSource);L(a,h,CompileShader);L(a,h,GetShaderiv);L(a,h,CreateProgram);L(a,h,AttachShader);L(a,h,LinkProgram);L(a,h,GetProgramiv);L(a,h,UseProgram);L(a,h,GenVertexArrays);L(a,h,BindVertexArray);L(a,h,GenBuffers);L(a,h,BindBuffer);L(a,h,BufferData);L(a,h,VertexAttribPointer);L(a,h,EnableVertexAttribArray);L(a,h,DrawElements);L(a,h,GetError);}
#undef L
static int eglsetup(void*h){EGLDisplay(*gd)(EGLNativeDisplayType)=dlsym(h,"eglGetDisplay");EGLBoolean(*in)(EGLDisplay,EGLint*,EGLint*)=dlsym(h,"eglInitialize");EGLBoolean(*ba)(EGLenum)=dlsym(h,"eglBindAPI");EGLBoolean(*gc)(EGLDisplay,EGLConfig*,EGLint,EGLint*)=dlsym(h,"eglGetConfigs");EGLContext(*cc)(EGLDisplay,EGLConfig,EGLContext,const EGLint*)=dlsym(h,"eglCreateContext");EGLSurface(*cp)(EGLDisplay,EGLConfig,const EGLint*)=dlsym(h,"eglCreatePbufferSurface");EGLBoolean(*mc)(EGLDisplay,EGLSurface,EGLSurface,EGLContext)=dlsym(h,"eglMakeCurrent");EGLDisplay d=gd(EGL_DEFAULT_DISPLAY);EGLint x,y;CHECK(in(d,&x,&y),"EGL initialize");CHECK(ba(EGL_OPENGL_API),"EGL OpenGL API");EGLConfig c;EGLint n;CHECK(gc(d,&c,1,&n)&&n,"EGL config");const EGLint ca[]={EGL_CONTEXT_MAJOR_VERSION,4,EGL_CONTEXT_MINOR_VERSION,6,EGL_NONE},pa[]={EGL_WIDTH,W,EGL_HEIGHT,H,EGL_NONE};EGLContext q=cc(d,c,EGL_NO_CONTEXT,ca);EGLSurface s=cp(d,c,pa);CHECK(q!=EGL_NO_CONTEXT&&s!=EGL_NO_SURFACE&&mc(d,s,s,q),"EGL current");return q!=EGL_NO_CONTEXT&&s!=EGL_NO_SURFACE;}
static GLuint prog(A*a){const char*vs="#version 330 core\nlayout(location=0)in vec2 p;void main(){gl_Position=vec4(p,0,1);}";const char*fs="#version 330 core\nout vec4 o;void main(){o=vec4(0,1,1,1);}";GLuint v=a->CreateShader(GL_VERTEX_SHADER),f=a->CreateShader(GL_FRAGMENT_SHADER);a->ShaderSource(v,1,&vs,0);a->ShaderSource(f,1,&fs,0);a->CompileShader(v);a->CompileShader(f);GLint x=0,y=0;a->GetShaderiv(v,GL_COMPILE_STATUS,&x);a->GetShaderiv(f,GL_COMPILE_STATUS,&y);CHECK(x&&y,"shaders compile");GLuint p=a->CreateProgram();a->AttachShader(p,v);a->AttachShader(p,f);a->LinkProgram(p);a->GetProgramiv(p,GL_LINK_STATUS,&x);CHECK(x,"program links");return p;}
static GLuint fbo(A*a){GLuint t,f;a->GenTextures(1,&t);a->BindTexture(GL_TEXTURE_2D,t);a->TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST);a->TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST);a->TexImage2D(GL_TEXTURE_2D,0,GL_RGBA8,W,H,0,GL_RGBA,GL_UNSIGNED_BYTE,0);a->GenFramebuffers(1,&f);a->BindFramebuffer(GL_FRAMEBUFFER,f);a->FramebufferTexture2D(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_TEXTURE_2D,t,0);CHECK(a->CheckFramebufferStatus(GL_FRAMEBUFFER)==GL_FRAMEBUFFER_COMPLETE,"FBO complete");return f;}
static unsigned cyan(A*a){uint8_t*p=malloc(W*H*4);a->Finish();a->ReadPixels(0,0,W,H,GL_RGBA,GL_UNSIGNED_BYTE,p);unsigned n=0;for(int i=0;i<W*H;i++)if(p[i*4]<80&&p[i*4+1]>150&&p[i*4+2]>150)n++;free(p);return n;}
static void common(A*a,GLuint f,GLuint p){a->BindFramebuffer(GL_FRAMEBUFFER,f);a->Viewport(0,0,W,H);a->Disable(GL_PRIMITIVE_RESTART);a->Disable(GL_PRIMITIVE_RESTART_FIXED_INDEX);a->Disable(GL_DEPTH_TEST);a->Disable(GL_CULL_FACE);a->ClearColor(0,0,0,1);a->Clear(GL_COLOR_BUFFER_BIT);a->UseProgram(p);}
static void u16(A*a,GLuint f,GLuint p){float*v=calloc(65536*2,sizeof(float));for(int i=0;i<6;i++)v[i]=3.0f;v[65535*2]=-0.78f;v[65535*2+1]=-0.72f;v[3*2]=.78f;v[3*2+1]=-.72f;v[4*2]=0;v[4*2+1]=.76f;uint16_t ix[]={0,1,2,0xffff,3,4};GLuint va,b,e;a->GenVertexArrays(1,&va);a->BindVertexArray(va);a->GenBuffers(1,&b);a->BindBuffer(GL_ARRAY_BUFFER,b);a->BufferData(GL_ARRAY_BUFFER,65536*2*sizeof(float),v,GL_STATIC_DRAW);free(v);a->VertexAttribPointer(0,2,GL_FLOAT,GL_FALSE,8,0);a->EnableVertexAttribArray(0);a->GenBuffers(1,&e);a->BindBuffer(GL_ELEMENT_ARRAY_BUFFER,e);a->BufferData(GL_ELEMENT_ARRAY_BUFFER,sizeof ix,ix,GL_STATIC_DRAW);common(a,f,p);a->DrawElements(GL_TRIANGLE_STRIP,6,GL_UNSIGNED_SHORT,0);CHECK(a->GetError()==GL_NO_ERROR,"U16 disabled-restart strip no GL error");unsigned n=cyan(a);CHECK(n>1000,"U16 0xffff is ordinary vertex when restart disabled on strip (%u cyan)",n);}
static void u8(A*a,GLuint f,GLuint p){float*v=calloc(256*2,sizeof(float));for(int i=0;i<6;i++)v[i]=3.0f;v[255*2]=-.78f;v[255*2+1]=-.72f;v[3*2]=.78f;v[3*2+1]=-.72f;v[4*2]=0;v[4*2+1]=.76f;uint8_t ix[]={0,1,2,0xff,3,4};GLuint va,b,e;a->GenVertexArrays(1,&va);a->BindVertexArray(va);a->GenBuffers(1,&b);a->BindBuffer(GL_ARRAY_BUFFER,b);a->BufferData(GL_ARRAY_BUFFER,256*2*sizeof(float),v,GL_STATIC_DRAW);free(v);a->VertexAttribPointer(0,2,GL_FLOAT,GL_FALSE,8,0);a->EnableVertexAttribArray(0);a->GenBuffers(1,&e);a->BindBuffer(GL_ELEMENT_ARRAY_BUFFER,e);a->BufferData(GL_ELEMENT_ARRAY_BUFFER,sizeof ix,ix,GL_STATIC_DRAW);common(a,f,p);a->DrawElements(GL_TRIANGLE_STRIP,6,GL_UNSIGNED_BYTE,0);CHECK(a->GetError()==GL_NO_ERROR,"U8 disabled-restart strip no GL error");unsigned n=cyan(a);CHECK(n>1000,"U8 0xff remains ordinary vertex after widening (%u cyan)",n);}
int main(int c,char**v){if(c!=2)return 2;void*h=dlopen(v[1],RTLD_NOW|RTLD_LOCAL);CHECK(h,"dlopen");if(!h)return 2;if(!eglsetup(h))return 1;A a;load(h,&a);GLuint f=fbo(&a),p=prog(&a);u8(&a,f,p);u16(&a,f,p);printf("RESTART_DISABLED_STRIP checks=%d failures=%d\n",checks,failures);return failures?1:0;}
