/* DirectMetal Minecraft 26.2 production API closure oracle.
 * Covers production-observed semantics not already closed by the domain suite:
 * stringi enumeration; float texture/sampler params + tex subimage/query;
 * framebuffer blit; bind-attrib-location; instanced array/base-vertex draws;
 * and resource deletion state.
 */
#include <dlfcn.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <EGL/egl.h>
#include <GL/glcorearb.h>

#define W 64
#define H 64
static int checks=0, failures=0;
#define CHECK(c,fmt,...) do{++checks;if(c)printf("ok  : " fmt "\n",##__VA_ARGS__);else{printf("FAIL: " fmt "\n",##__VA_ARGS__);++failures;}}while(0)

typedef struct API {
 const GLubyte*(*GetString)(GLenum); const GLubyte*(*GetStringi)(GLenum,GLuint); GLenum(*GetError)(void); void(*GetIntegerv)(GLenum,GLint*); void(*Finish)(void);
 void(*Viewport)(GLint,GLint,GLsizei,GLsizei); void(*ClearColor)(GLfloat,GLfloat,GLfloat,GLfloat); void(*Clear)(GLbitfield); void(*ReadPixels)(GLint,GLint,GLsizei,GLsizei,GLenum,GLenum,void*);
 void(*GenTextures)(GLsizei,GLuint*); void(*BindTexture)(GLenum,GLuint); void(*TexImage2D)(GLenum,GLint,GLint,GLsizei,GLsizei,GLint,GLenum,GLenum,const void*); void(*TexSubImage2D)(GLenum,GLint,GLint,GLint,GLsizei,GLsizei,GLenum,GLenum,const void*); void(*TexParameterf)(GLenum,GLenum,GLfloat); void(*GetTexLevelParameteriv)(GLenum,GLint,GLenum,GLint*); void(*DeleteTextures)(GLsizei,const GLuint*); GLboolean(*IsTexture)(GLuint);
 void(*GenSamplers)(GLsizei,GLuint*); void(*BindSampler)(GLuint,GLuint); void(*SamplerParameterf)(GLuint,GLenum,GLfloat); void(*DeleteSamplers)(GLsizei,const GLuint*); GLboolean(*IsSampler)(GLuint); void(*ActiveTexture)(GLenum);
 void(*GenFramebuffers)(GLsizei,GLuint*); void(*BindFramebuffer)(GLenum,GLuint); void(*FramebufferTexture2D)(GLenum,GLenum,GLenum,GLuint,GLint); GLenum(*CheckFramebufferStatus)(GLenum); void(*DrawBuffer)(GLenum); void(*ReadBuffer)(GLenum); void(*BlitFramebuffer)(GLint,GLint,GLint,GLint,GLint,GLint,GLint,GLint,GLbitfield,GLenum); void(*DeleteFramebuffers)(GLsizei,const GLuint*); GLboolean(*IsFramebuffer)(GLuint);
 GLuint(*CreateShader)(GLenum); void(*ShaderSource)(GLuint,GLsizei,const GLchar*const*,const GLint*); void(*CompileShader)(GLuint); void(*GetShaderiv)(GLuint,GLenum,GLint*); void(*DeleteShader)(GLuint);
 GLuint(*CreateProgram)(void); void(*BindAttribLocation)(GLuint,GLuint,const GLchar*); void(*AttachShader)(GLuint,GLuint); void(*LinkProgram)(GLuint); void(*GetProgramiv)(GLuint,GLenum,GLint*); void(*GetProgramInfoLog)(GLuint,GLsizei,GLsizei*,GLchar*); void(*UseProgram)(GLuint); GLint(*GetUniformLocation)(GLuint,const GLchar*); void(*Uniform1i)(GLint,GLint); void(*DeleteProgram)(GLuint); GLboolean(*IsProgram)(GLuint);
 void(*GenVertexArrays)(GLsizei,GLuint*); void(*BindVertexArray)(GLuint); void(*EnableVertexAttribArray)(GLuint); void(*VertexAttribPointer)(GLuint,GLint,GLenum,GLboolean,GLsizei,const void*);
 void(*GenBuffers)(GLsizei,GLuint*); void(*BindBuffer)(GLenum,GLuint); void(*BufferData)(GLenum,GLsizeiptr,const void*,GLenum); void(*DeleteBuffers)(GLsizei,const GLuint*); GLboolean(*IsBuffer)(GLuint);
 void(*DrawArrays)(GLenum,GLint,GLsizei); void(*DrawArraysInstanced)(GLenum,GLint,GLsizei,GLsizei); void(*DrawElementsInstancedBaseVertex)(GLenum,GLsizei,GLenum,const void*,GLsizei,GLint);
} API;
#define L(a,h,f) do{(a)->f=(__typeof__((a)->f))dlsym((h),"gl"#f);CHECK((a)->f!=NULL,"resolve gl%s",#f);}while(0)
static int load(void*h,API*a){memset(a,0,sizeof(*a));
 L(a,h,GetString);L(a,h,GetStringi);L(a,h,GetError);L(a,h,GetIntegerv);L(a,h,Finish);L(a,h,Viewport);L(a,h,ClearColor);L(a,h,Clear);L(a,h,ReadPixels);
 L(a,h,GenTextures);L(a,h,BindTexture);L(a,h,TexImage2D);L(a,h,TexSubImage2D);L(a,h,TexParameterf);L(a,h,GetTexLevelParameteriv);L(a,h,DeleteTextures);L(a,h,IsTexture);
 L(a,h,GenSamplers);L(a,h,BindSampler);L(a,h,SamplerParameterf);L(a,h,DeleteSamplers);L(a,h,IsSampler);L(a,h,ActiveTexture);
 L(a,h,GenFramebuffers);L(a,h,BindFramebuffer);L(a,h,FramebufferTexture2D);L(a,h,CheckFramebufferStatus);L(a,h,DrawBuffer);L(a,h,ReadBuffer);L(a,h,BlitFramebuffer);L(a,h,DeleteFramebuffers);L(a,h,IsFramebuffer);
 L(a,h,CreateShader);L(a,h,ShaderSource);L(a,h,CompileShader);L(a,h,GetShaderiv);L(a,h,DeleteShader);L(a,h,CreateProgram);L(a,h,BindAttribLocation);L(a,h,AttachShader);L(a,h,LinkProgram);L(a,h,GetProgramiv);L(a,h,GetProgramInfoLog);L(a,h,UseProgram);L(a,h,GetUniformLocation);L(a,h,Uniform1i);L(a,h,DeleteProgram);L(a,h,IsProgram);
 L(a,h,GenVertexArrays);L(a,h,BindVertexArray);L(a,h,EnableVertexAttribArray);L(a,h,VertexAttribPointer);L(a,h,GenBuffers);L(a,h,BindBuffer);L(a,h,BufferData);L(a,h,DeleteBuffers);L(a,h,IsBuffer);L(a,h,DrawArrays);L(a,h,DrawArraysInstanced);L(a,h,DrawElementsInstancedBaseVertex);
 return failures==0;}
#undef L

static int egl_setup(void*h){EGLDisplay(*gd)(EGLNativeDisplayType)=dlsym(h,"eglGetDisplay");EGLBoolean(*init)(EGLDisplay,EGLint*,EGLint*)=dlsym(h,"eglInitialize");EGLBoolean(*ba)(EGLenum)=dlsym(h,"eglBindAPI");EGLBoolean(*gc)(EGLDisplay,EGLConfig*,EGLint,EGLint*)=dlsym(h,"eglGetConfigs");EGLContext(*cc)(EGLDisplay,EGLConfig,EGLContext,const EGLint*)=dlsym(h,"eglCreateContext");EGLSurface(*ps)(EGLDisplay,EGLConfig,const EGLint*)=dlsym(h,"eglCreatePbufferSurface");EGLBoolean(*mc)(EGLDisplay,EGLSurface,EGLSurface,EGLContext)=dlsym(h,"eglMakeCurrent");CHECK(gd&&init&&ba&&gc&&cc&&ps&&mc,"resolve EGL");if(!gd||!init||!ba||!gc||!cc||!ps||!mc)return 0;EGLDisplay d=gd(EGL_DEFAULT_DISPLAY);EGLint x=0,y=0;CHECK(d!=EGL_NO_DISPLAY&&init(d,&x,&y),"initialize EGL");CHECK(ba(EGL_OPENGL_API),"bind OpenGL API");EGLConfig c=0;EGLint n=0;CHECK(gc(d,&c,1,&n)&&n>0,"get config");const EGLint ca[]={EGL_CONTEXT_MAJOR_VERSION,3,EGL_CONTEXT_MINOR_VERSION,3,EGL_NONE},pa[]={EGL_WIDTH,W,EGL_HEIGHT,H,EGL_NONE};EGLContext cx=cc(d,c,EGL_NO_CONTEXT,ca);EGLSurface s=ps(d,c,pa);CHECK(cx!=EGL_NO_CONTEXT&&s!=EGL_NO_SURFACE,"create context/pbuffer");CHECK(mc(d,s,s,cx),"make current");return cx!=EGL_NO_CONTEXT&&s!=EGL_NO_SURFACE;}
static int near4(const uint8_t*p,int r,int g,int b,int a){return abs((int)p[0]-r)<=5&&abs((int)p[1]-g)<=5&&abs((int)p[2]-b)<=5&&abs((int)p[3]-a)<=5;}
static void read_center(API*a,uint8_t p[4]){a->Finish();a->ReadPixels(W/2,H/2,1,1,GL_RGBA,GL_UNSIGNED_BYTE,p);a->Finish();}
static GLuint make_tex(API*a,int w,int h,const uint8_t*data){GLuint t=0;a->GenTextures(1,&t);a->BindTexture(GL_TEXTURE_2D,t);a->TexParameterf(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,(GLfloat)GL_NEAREST);a->TexParameterf(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,(GLfloat)GL_NEAREST);a->TexImage2D(GL_TEXTURE_2D,0,GL_RGBA8,w,h,0,GL_RGBA,GL_UNSIGNED_BYTE,data);return t;}
static GLuint make_fbo(API*a,GLuint tex){GLuint f=0;a->GenFramebuffers(1,&f);a->BindFramebuffer(GL_FRAMEBUFFER,f);a->FramebufferTexture2D(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_TEXTURE_2D,tex,0);CHECK(a->CheckFramebufferStatus(GL_FRAMEBUFFER)==GL_FRAMEBUFFER_COMPLETE,"FBO %u complete",f);return f;}
static GLuint shader(API*a,GLenum type,const char*src){GLuint s=a->CreateShader(type);a->ShaderSource(s,1,&src,0);a->CompileShader(s);GLint ok=0;a->GetShaderiv(s,GL_COMPILE_STATUS,&ok);CHECK(ok,"shader %u compiles",s);return s;}
static GLuint texture_program(API*a){const char*vs="#version 330 core\nvoid main(){const vec2 p[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));gl_Position=vec4(p[gl_VertexID],0,1);}\n";const char*fs="#version 330 core\nuniform sampler2D tex;out vec4 o;void main(){o=texture(tex,vec2(1.25,0.5));}\n";GLuint sv=shader(a,GL_VERTEX_SHADER,vs),sf=shader(a,GL_FRAGMENT_SHADER,fs),p=a->CreateProgram();a->AttachShader(p,sv);a->AttachShader(p,sf);a->LinkProgram(p);GLint ok=0;a->GetProgramiv(p,GL_LINK_STATUS,&ok);CHECK(ok,"texture program links");a->DeleteShader(sv);a->DeleteShader(sf);return p;}
typedef struct V{float x,y;float r,g,b;}V;
static GLuint attrib_program(API*a){const char*vs="#version 330 core\nin vec2 pos;in vec3 color;out vec3 c;void main(){gl_Position=vec4(pos,0,1);c=color;}\n";const char*fs="#version 330 core\nin vec3 c;out vec4 o;void main(){o=vec4(c,1);}\n";GLuint sv=shader(a,GL_VERTEX_SHADER,vs),sf=shader(a,GL_FRAGMENT_SHADER,fs),p=a->CreateProgram();a->BindAttribLocation(p,3,"pos");a->BindAttribLocation(p,5,"color");a->AttachShader(p,sv);a->AttachShader(p,sf);a->LinkProgram(p);GLint ok=0;a->GetProgramiv(p,GL_LINK_STATUS,&ok);CHECK(ok,"bind-attrib program links");char log[128]={0};GLsizei len=-1;a->GetProgramInfoLog(p,sizeof(log),&len,log);CHECK(len>=0&&len<(GLsizei)sizeof(log),"successful program info log is bounded (%d)",(int)len);a->DeleteShader(sv);a->DeleteShader(sf);return p;}

int main(int ac,char**av){const char*path=ac>1?av[1]:"./libmithril.dylib";void*h=dlopen(path,RTLD_NOW|RTLD_GLOBAL);CHECK(h!=0,"dlopen %s",path);if(!h)return 2;if(!egl_setup(h))return 2;API a;if(!load(h,&a))return 2;const char*v=(const char*)a.GetString(GL_VERSION);CHECK(v&&strstr(v,"3.3.0")&&strstr(v,"DirectMetal"),"DirectMetal GL 3.3 active (%s)",v?v:"null");while(a.GetError()!=GL_NO_ERROR){}
 GLint ne=0;a.GetIntegerv(GL_NUM_EXTENSIONS,&ne);CHECK(ne>0,"extension count positive (%d)",ne);int saw=0;for(GLint i=0;i<ne;i++){const char*e=(const char*)a.GetStringi(GL_EXTENSIONS,(GLuint)i);CHECK(e&&*e,"extension[%d] nonempty",i);if(e&&strcmp(e,"GL_MITHRIL_wrapper")==0)saw=1;}CHECK(saw,"GetStringi enumerates GL_MITHRIL_wrapper");
 const uint8_t rg[8]={255,0,0,255,0,255,0,255};a.ActiveTexture(GL_TEXTURE0);GLuint sampleTex=make_tex(&a,2,1,rg);a.TexParameterf(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,(GLfloat)GL_REPEAT);a.TexParameterf(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,(GLfloat)GL_CLAMP_TO_EDGE);GLint tw=0,th=0,ti=0;a.GetTexLevelParameteriv(GL_TEXTURE_2D,0,GL_TEXTURE_WIDTH,&tw);a.GetTexLevelParameteriv(GL_TEXTURE_2D,0,GL_TEXTURE_HEIGHT,&th);a.GetTexLevelParameteriv(GL_TEXTURE_2D,0,GL_TEXTURE_INTERNAL_FORMAT,&ti);CHECK(tw==2&&th==1&&ti==GL_RGBA8,"texture level query = 2x1 RGBA8 (%d,%d,0x%x)",tw,th,ti);
 GLuint targetTex=make_tex(&a,W,H,0),targetFbo=make_fbo(&a,targetTex),vao=0;a.GenVertexArrays(1,&vao);a.BindVertexArray(vao);GLuint tp=texture_program(&a);a.UseProgram(tp);GLint ul=a.GetUniformLocation(tp,"tex");CHECK(ul>=0,"texture sampler uniform location");a.Uniform1i(ul,0);a.Viewport(0,0,W,H);a.BindFramebuffer(GL_FRAMEBUFFER,targetFbo);a.ActiveTexture(GL_TEXTURE0);a.BindTexture(GL_TEXTURE_2D,sampleTex);a.BindSampler(0,0);a.ClearColor(0,0,0,1);a.Clear(GL_COLOR_BUFFER_BIT);a.DrawArrays(GL_TRIANGLES,0,3);uint8_t px[4]={0};read_center(&a,px);CHECK(near4(px,255,0,0,255),"TexParameterf REPEAT samples red (%u,%u,%u,%u)",px[0],px[1],px[2],px[3]);
 GLuint smp=0;a.GenSamplers(1,&smp);a.SamplerParameterf(smp,GL_TEXTURE_MIN_FILTER,(GLfloat)GL_NEAREST);a.SamplerParameterf(smp,GL_TEXTURE_MAG_FILTER,(GLfloat)GL_NEAREST);a.SamplerParameterf(smp,GL_TEXTURE_WRAP_S,(GLfloat)GL_CLAMP_TO_EDGE);a.SamplerParameterf(smp,GL_TEXTURE_WRAP_T,(GLfloat)GL_CLAMP_TO_EDGE);a.BindSampler(0,smp);a.Clear(GL_COLOR_BUFFER_BIT);a.DrawArrays(GL_TRIANGLES,0,3);read_center(&a,px);CHECK(near4(px,0,255,0,255),"SamplerParameterf CLAMP overrides texture -> green (%u,%u,%u,%u)",px[0],px[1],px[2],px[3]);const uint8_t blue[4]={0,0,255,255};a.BindTexture(GL_TEXTURE_2D,sampleTex);a.TexSubImage2D(GL_TEXTURE_2D,0,1,0,1,1,GL_RGBA,GL_UNSIGNED_BYTE,blue);a.Clear(GL_COLOR_BUFFER_BIT);a.DrawArrays(GL_TRIANGLES,0,3);read_center(&a,px);CHECK(near4(px,0,0,255,255),"TexSubImage2D update reaches sampled GPU texel (%u,%u,%u,%u)",px[0],px[1],px[2],px[3]);a.BindSampler(0,0);
 GLuint srcTex=make_tex(&a,W,H,0),dstTex=make_tex(&a,W,H,0),srcFbo=make_fbo(&a,srcTex),dstFbo=make_fbo(&a,dstTex);a.BindFramebuffer(GL_DRAW_FRAMEBUFFER,srcFbo);a.DrawBuffer(GL_COLOR_ATTACHMENT0);a.ClearColor(1,0,1,1);a.Clear(GL_COLOR_BUFFER_BIT);a.BindFramebuffer(GL_READ_FRAMEBUFFER,srcFbo);a.ReadBuffer(GL_COLOR_ATTACHMENT0);a.BindFramebuffer(GL_DRAW_FRAMEBUFFER,dstFbo);a.DrawBuffer(GL_COLOR_ATTACHMENT0);a.BlitFramebuffer(0,0,W,H,0,0,W,H,GL_COLOR_BUFFER_BIT,GL_NEAREST);a.BindFramebuffer(GL_FRAMEBUFFER,dstFbo);a.ReadBuffer(GL_COLOR_ATTACHMENT0);read_center(&a,px);CHECK(near4(px,255,0,255,255),"BlitFramebuffer copies magenta pixel (%u,%u,%u,%u)",px[0],px[1],px[2],px[3]);
 GLuint ap=attrib_program(&a);a.UseProgram(ap);V verts[4]={{0,0,0,0,0},{-.8f,-.8f,0,1,0},{.8f,-.8f,0,1,0},{0,.8f,0,1,0}};GLuint vbo=0,ebo=0;a.GenBuffers(1,&vbo);a.BindBuffer(GL_ARRAY_BUFFER,vbo);a.BufferData(GL_ARRAY_BUFFER,sizeof(verts),verts,GL_STATIC_DRAW);a.GenBuffers(1,&ebo);a.BindBuffer(GL_ELEMENT_ARRAY_BUFFER,ebo);const uint16_t idx[3]={0,1,2};a.BufferData(GL_ELEMENT_ARRAY_BUFFER,sizeof(idx),idx,GL_STATIC_DRAW);a.BindVertexArray(vao);a.BindBuffer(GL_ARRAY_BUFFER,vbo);a.VertexAttribPointer(3,2,GL_FLOAT,GL_FALSE,sizeof(V),(const void*)0);a.EnableVertexAttribArray(3);a.VertexAttribPointer(5,3,GL_FLOAT,GL_FALSE,sizeof(V),(const void*)(2*sizeof(float)));a.EnableVertexAttribArray(5);a.BindBuffer(GL_ELEMENT_ARRAY_BUFFER,ebo);a.BindFramebuffer(GL_FRAMEBUFFER,targetFbo);a.Viewport(0,0,W,H);a.ClearColor(0,0,0,1);a.Clear(GL_COLOR_BUFFER_BIT);a.DrawArraysInstanced(GL_TRIANGLES,1,3,2);read_center(&a,px);CHECK(near4(px,0,255,0,255),"DrawArraysInstanced + BindAttribLocation produces green (%u,%u,%u,%u)",px[0],px[1],px[2],px[3]);a.Clear(GL_COLOR_BUFFER_BIT);a.DrawElementsInstancedBaseVertex(GL_TRIANGLES,3,GL_UNSIGNED_SHORT,(const void*)0,2,1);read_center(&a,px);CHECK(near4(px,0,255,0,255),"DrawElementsInstancedBaseVertex baseVertex=1 produces green (%u,%u,%u,%u)",px[0],px[1],px[2],px[3]);
 a.UseProgram(0);a.BindSampler(0,0);a.BindFramebuffer(GL_FRAMEBUFFER,0);a.BindBuffer(GL_ARRAY_BUFFER,0);a.BindBuffer(GL_ELEMENT_ARRAY_BUFFER,0);a.BindTexture(GL_TEXTURE_2D,0);a.DeleteSamplers(1,&smp);CHECK(a.IsSampler(smp)==GL_FALSE,"deleted sampler is no longer an object");a.DeleteBuffers(1,&vbo);a.DeleteBuffers(1,&ebo);CHECK(a.IsBuffer(vbo)==GL_FALSE&&a.IsBuffer(ebo)==GL_FALSE,"deleted buffers are no longer objects");a.DeleteFramebuffers(1,&srcFbo);a.DeleteFramebuffers(1,&dstFbo);CHECK(a.IsFramebuffer(srcFbo)==GL_FALSE&&a.IsFramebuffer(dstFbo)==GL_FALSE,"deleted framebuffer names are no longer objects");a.DeleteTextures(1,&srcTex);a.DeleteTextures(1,&dstTex);CHECK(a.IsTexture(srcTex)==GL_FALSE&&a.IsTexture(dstTex)==GL_FALSE,"deleted texture names are no longer objects");a.DeleteProgram(ap);CHECK(a.IsProgram(ap)==GL_FALSE,"deleted program is no longer an object");a.DeleteProgram(tp);CHECK(a.IsProgram(tp)==GL_FALSE,"second deleted program is no longer an object");CHECK(a.GetError()==GL_NO_ERROR,"production closure oracle ends without GL error");printf("PRODUCTION API CLOSURE SMOKE: %d checks, %d failure(s)\n",checks,failures);if(!failures)printf("PRODUCTION API CLOSURE SMOKE ALL PASSED\n");return failures?1:0;}
