/* DirectMetal GL 3.3 sampler-object override oracle. */
#include <dlfcn.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <EGL/egl.h>
#include <GL/glcorearb.h>
#define W 64
#define H 64
static int checks=0, failures=0;
#define CHECK(c,fmt,...) do { ++checks; if(c) printf("ok  : " fmt "\n", ##__VA_ARGS__); else { printf("FAIL: " fmt "\n", ##__VA_ARGS__); ++failures; } } while(0)
typedef struct API {const GLubyte*(*GetString)(GLenum);GLenum(*GetError)(void);void(*Finish)(void);void(*Viewport)(GLint,GLint,GLsizei,GLsizei);void(*ClearColor)(GLfloat,GLfloat,GLfloat,GLfloat);void(*Clear)(GLbitfield);void(*ReadPixels)(GLint,GLint,GLsizei,GLsizei,GLenum,GLenum,void*);void(*ActiveTexture)(GLenum);void(*GenTextures)(GLsizei,GLuint*);void(*BindTexture)(GLenum,GLuint);void(*TexImage2D)(GLenum,GLint,GLint,GLsizei,GLsizei,GLint,GLenum,GLenum,const void*);void(*TexParameteri)(GLenum,GLenum,GLint);void(*GenSamplers)(GLsizei,GLuint*);void(*BindSampler)(GLuint,GLuint);void(*SamplerParameteri)(GLuint,GLenum,GLint);void(*DeleteSamplers)(GLsizei,const GLuint*);void(*GenFramebuffers)(GLsizei,GLuint*);void(*BindFramebuffer)(GLenum,GLuint);void(*FramebufferTexture2D)(GLenum,GLenum,GLenum,GLuint,GLint);GLenum(*CheckFramebufferStatus)(GLenum);GLuint(*CreateShader)(GLenum);void(*ShaderSource)(GLuint,GLsizei,const GLchar* const*,const GLint*);void(*CompileShader)(GLuint);void(*GetShaderiv)(GLuint,GLenum,GLint*);GLuint(*CreateProgram)(void);void(*AttachShader)(GLuint,GLuint);void(*LinkProgram)(GLuint);void(*GetProgramiv)(GLuint,GLenum,GLint*);void(*UseProgram)(GLuint);GLint(*GetUniformLocation)(GLuint,const GLchar*);void(*Uniform1i)(GLint,GLint);void(*GenVertexArrays)(GLsizei,GLuint*);void(*BindVertexArray)(GLuint);void(*DrawArrays)(GLenum,GLint,GLsizei);}API;
#define LOAD(a,h,f) do{(a)->f=(__typeof__((a)->f))dlsym((h),"gl"#f);CHECK((a)->f!=NULL,"resolve gl%s",#f);}while(0)
static int load_api(void*h,API*a){memset(a,0,sizeof(*a));LOAD(a,h,GetString);LOAD(a,h,GetError);LOAD(a,h,Finish);LOAD(a,h,Viewport);LOAD(a,h,ClearColor);LOAD(a,h,Clear);LOAD(a,h,ReadPixels);LOAD(a,h,ActiveTexture);LOAD(a,h,GenTextures);LOAD(a,h,BindTexture);LOAD(a,h,TexImage2D);LOAD(a,h,TexParameteri);LOAD(a,h,GenSamplers);LOAD(a,h,BindSampler);LOAD(a,h,SamplerParameteri);LOAD(a,h,DeleteSamplers);LOAD(a,h,GenFramebuffers);LOAD(a,h,BindFramebuffer);LOAD(a,h,FramebufferTexture2D);LOAD(a,h,CheckFramebufferStatus);LOAD(a,h,CreateShader);LOAD(a,h,ShaderSource);LOAD(a,h,CompileShader);LOAD(a,h,GetShaderiv);LOAD(a,h,CreateProgram);LOAD(a,h,AttachShader);LOAD(a,h,LinkProgram);LOAD(a,h,GetProgramiv);LOAD(a,h,UseProgram);LOAD(a,h,GetUniformLocation);LOAD(a,h,Uniform1i);LOAD(a,h,GenVertexArrays);LOAD(a,h,BindVertexArray);LOAD(a,h,DrawArrays);return failures==0;}
#undef LOAD
static int egl_setup(void*h){EGLDisplay(*gd)(EGLNativeDisplayType)=dlsym(h,"eglGetDisplay");EGLBoolean(*init)(EGLDisplay,EGLint*,EGLint*)=dlsym(h,"eglInitialize");EGLBoolean(*ba)(EGLenum)=dlsym(h,"eglBindAPI");EGLBoolean(*gc)(EGLDisplay,EGLConfig*,EGLint,EGLint*)=dlsym(h,"eglGetConfigs");EGLContext(*cc)(EGLDisplay,EGLConfig,EGLContext,const EGLint*)=dlsym(h,"eglCreateContext");EGLSurface(*ps)(EGLDisplay,EGLConfig,const EGLint*)=dlsym(h,"eglCreatePbufferSurface");EGLBoolean(*mc)(EGLDisplay,EGLSurface,EGLSurface,EGLContext)=dlsym(h,"eglMakeCurrent");CHECK(gd&&init&&ba&&gc&&cc&&ps&&mc,"resolve EGL entry points");if(!gd||!init||!ba||!gc||!cc||!ps||!mc)return 0;EGLDisplay d=gd(EGL_DEFAULT_DISPLAY);EGLint ma=0,mi=0;CHECK(d!=EGL_NO_DISPLAY&&init(d,&ma,&mi),"initialize EGL");CHECK(ba(EGL_OPENGL_API),"bind OpenGL API");EGLConfig cfg=0;EGLint n=0;CHECK(gc(d,&cfg,1,&n)&&n>0,"get EGL config");const EGLint ca[]={EGL_CONTEXT_MAJOR_VERSION,3,EGL_CONTEXT_MINOR_VERSION,3,EGL_NONE};const EGLint pa[]={EGL_WIDTH,W,EGL_HEIGHT,H,EGL_NONE};EGLContext c=cc(d,cfg,EGL_NO_CONTEXT,ca);EGLSurface s=ps(d,cfg,pa);CHECK(c!=EGL_NO_CONTEXT&&s!=EGL_NO_SURFACE,"create context/pbuffer");CHECK(mc(d,s,s,c),"make current");return c!=EGL_NO_CONTEXT&&s!=EGL_NO_SURFACE;}
static GLuint make_program(API*a){const char*vs="#version 330 core\nvoid main(){const vec2 p[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));gl_Position=vec4(p[gl_VertexID],0,1);}\n";const char*fs="#version 330 core\nuniform sampler2D tex;out vec4 o;void main(){o=texture(tex,vec2(1.25,0.5));}\n";GLuint sv=a->CreateShader(GL_VERTEX_SHADER),sf=a->CreateShader(GL_FRAGMENT_SHADER);a->ShaderSource(sv,1,&vs,0);a->ShaderSource(sf,1,&fs,0);a->CompileShader(sv);a->CompileShader(sf);GLint vc=0,fc=0;a->GetShaderiv(sv,GL_COMPILE_STATUS,&vc);a->GetShaderiv(sf,GL_COMPILE_STATUS,&fc);CHECK(vc&&fc,"sampler shader pair compiles");GLuint p=a->CreateProgram();a->AttachShader(p,sv);a->AttachShader(p,sf);a->LinkProgram(p);GLint linked=0;a->GetProgramiv(p,GL_LINK_STATUS,&linked);CHECK(linked,"sampler program links");return p;}
static GLuint make_target(API*a){GLuint t=0,f=0;a->GenTextures(1,&t);a->BindTexture(GL_TEXTURE_2D,t);a->TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST);a->TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST);a->TexImage2D(GL_TEXTURE_2D,0,GL_RGBA8,W,H,0,GL_RGBA,GL_UNSIGNED_BYTE,0);a->GenFramebuffers(1,&f);a->BindFramebuffer(GL_FRAMEBUFFER,f);a->FramebufferTexture2D(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_TEXTURE_2D,t,0);CHECK(a->CheckFramebufferStatus(GL_FRAMEBUFFER)==GL_FRAMEBUFFER_COMPLETE,"FBO complete");return f;}
static int is_red(const uint8_t*p){return p[0]>240&&p[1]<15&&p[2]<15&&p[3]>240;}static int is_green(const uint8_t*p){return p[1]>240&&p[0]<15&&p[2]<15&&p[3]>240;}static void read_center(API*a,uint8_t p[4]){a->Finish();a->ReadPixels(W/2,H/2,1,1,GL_RGBA,GL_UNSIGNED_BYTE,p);a->Finish();}
int main(int argc,char**argv){const char*path=argc>1?argv[1]:"./libmithril.dylib";void*h=dlopen(path,RTLD_NOW|RTLD_GLOBAL);CHECK(h!=NULL,"dlopen %s",path);if(!h)return 2;if(!egl_setup(h))return 2;API a;if(!load_api(h,&a))return 2;const char*v=(const char*)a.GetString(GL_VERSION);CHECK(v&&strstr(v,"3.3.0")&&strstr(v,"DirectMetal"),"DirectMetal GL 3.3 active (%s)",v?v:"null");while(a.GetError()!=GL_NO_ERROR){}GLuint target=make_target(&a),prog=make_program(&a),vao=0;a.GenVertexArrays(1,&vao);a.BindVertexArray(vao);a.UseProgram(prog);GLint loc=a.GetUniformLocation(prog,"tex");CHECK(loc>=0,"sampler uniform location (%d)",loc);a.Uniform1i(loc,0);a.Viewport(0,0,W,H);const uint8_t texels[8]={255,0,0,255,0,255,0,255};GLuint tex=0;a.GenTextures(1,&tex);a.ActiveTexture(GL_TEXTURE0);a.BindTexture(GL_TEXTURE_2D,tex);a.TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST);a.TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST);a.TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_REPEAT);a.TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);a.TexImage2D(GL_TEXTURE_2D,0,GL_RGBA8,2,1,0,GL_RGBA,GL_UNSIGNED_BYTE,texels);GLuint smp=0;a.GenSamplers(1,&smp);a.SamplerParameteri(smp,GL_TEXTURE_MIN_FILTER,GL_NEAREST);a.SamplerParameteri(smp,GL_TEXTURE_MAG_FILTER,GL_NEAREST);a.SamplerParameteri(smp,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE);a.SamplerParameteri(smp,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);uint8_t px[4]={0};a.BindFramebuffer(GL_FRAMEBUFFER,target);a.BindSampler(0,smp);a.ClearColor(0,0,0,1);a.Clear(GL_COLOR_BUFFER_BIT);a.DrawArrays(GL_TRIANGLES,0,3);read_center(&a,px);CHECK(is_green(px),"bound sampler overrides texture REPEAT with CLAMP_TO_EDGE -> green (%u,%u,%u,%u)",px[0],px[1],px[2],px[3]);a.BindSampler(0,0);a.Clear(GL_COLOR_BUFFER_BIT);a.DrawArrays(GL_TRIANGLES,0,3);read_center(&a,px);CHECK(is_red(px),"unbinding sampler restores texture REPEAT -> red (%u,%u,%u,%u)",px[0],px[1],px[2],px[3]);CHECK(a.GetError()==GL_NO_ERROR,"sampler oracle ends without GL error");a.DeleteSamplers(1,&smp);printf("SAMPLER SEMANTICS SMOKE: %d checks, %d failure(s)\n",checks,failures);if(!failures)printf("SAMPLER SEMANTICS SMOKE ALL PASSED\n");return failures?1:0;}
