/* DirectMetal U32 maximum-index representability oracle.
 * No vertex buffer is used: the VS maps uint(gl_VertexID)==0xffffffffu to a
 * real position, so the test can exercise the full U32 index domain without a
 * multi-gigabyte VBO. The triangle-list control establishes that Metal keeps
 * max-U32 as an ordinary index for list topology. Triangle/line strips then
 * cover the OpenGL-vs-Metal disabled-restart mismatch, and the programmable
 * restart case proves a custom restart token can coexist with an ordinary
 * 0xffffffff index without remap collision.
 */
#include <dlfcn.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <EGL/egl.h>
#include <GL/glcorearb.h>
#ifndef GL_PRIMITIVE_RESTART_FIXED_INDEX
#define GL_PRIMITIVE_RESTART_FIXED_INDEX 0x8D69
#endif
#define W 128
#define H 96
static int checks, failures;
#define CHECK(c,fmt,...) do{++checks;if(c)printf("ok  : " fmt "\n",##__VA_ARGS__);else{printf("FAIL: " fmt "\n",##__VA_ARGS__);++failures;}}while(0)
typedef struct A{void(*Enable)(GLenum);void(*Disable)(GLenum);void(*PrimitiveRestartIndex)(GLuint);void(*Viewport)(GLint,GLint,GLsizei,GLsizei);void(*ClearColor)(GLfloat,GLfloat,GLfloat,GLfloat);void(*Clear)(GLbitfield);void(*Finish)(void);void(*ReadPixels)(GLint,GLint,GLsizei,GLsizei,GLenum,GLenum,void*);void(*GenTextures)(GLsizei,GLuint*);void(*BindTexture)(GLenum,GLuint);void(*TexParameteri)(GLenum,GLenum,GLint);void(*TexImage2D)(GLenum,GLint,GLint,GLsizei,GLsizei,GLint,GLenum,GLenum,const void*);void(*GenFramebuffers)(GLsizei,GLuint*);void(*BindFramebuffer)(GLenum,GLuint);void(*FramebufferTexture2D)(GLenum,GLenum,GLenum,GLuint,GLint);GLenum(*CheckFramebufferStatus)(GLenum);GLuint(*CreateShader)(GLenum);void(*ShaderSource)(GLuint,GLsizei,const GLchar*const*,const GLint*);void(*CompileShader)(GLuint);void(*GetShaderiv)(GLuint,GLenum,GLint*);void(*GetShaderInfoLog)(GLuint,GLsizei,GLsizei*,GLchar*);GLuint(*CreateProgram)(void);void(*AttachShader)(GLuint,GLuint);void(*LinkProgram)(GLuint);void(*GetProgramiv)(GLuint,GLenum,GLint*);void(*GetProgramInfoLog)(GLuint,GLsizei,GLsizei*,GLchar*);void(*UseProgram)(GLuint);void(*GenVertexArrays)(GLsizei,GLuint*);void(*BindVertexArray)(GLuint);void(*GenBuffers)(GLsizei,GLuint*);void(*BindBuffer)(GLenum,GLuint);void(*BufferData)(GLenum,GLsizeiptr,const void*,GLenum);void(*DrawElements)(GLenum,GLsizei,GLenum,const void*);GLenum(*GetError)(void);}A;
#define L(a,h,f) do{(a)->f=(__typeof__((a)->f))dlsym(h,"gl"#f);CHECK((a)->f,"resolve gl%s",#f);}while(0)
static void load(void*h,A*a){memset(a,0,sizeof(*a));L(a,h,Enable);L(a,h,Disable);L(a,h,PrimitiveRestartIndex);L(a,h,Viewport);L(a,h,ClearColor);L(a,h,Clear);L(a,h,Finish);L(a,h,ReadPixels);L(a,h,GenTextures);L(a,h,BindTexture);L(a,h,TexParameteri);L(a,h,TexImage2D);L(a,h,GenFramebuffers);L(a,h,BindFramebuffer);L(a,h,FramebufferTexture2D);L(a,h,CheckFramebufferStatus);L(a,h,CreateShader);L(a,h,ShaderSource);L(a,h,CompileShader);L(a,h,GetShaderiv);L(a,h,GetShaderInfoLog);L(a,h,CreateProgram);L(a,h,AttachShader);L(a,h,LinkProgram);L(a,h,GetProgramiv);L(a,h,GetProgramInfoLog);L(a,h,UseProgram);L(a,h,GenVertexArrays);L(a,h,BindVertexArray);L(a,h,GenBuffers);L(a,h,BindBuffer);L(a,h,BufferData);L(a,h,DrawElements);L(a,h,GetError);}
#undef L
static int eglsetup(void*h){EGLDisplay(*gd)(EGLNativeDisplayType)=dlsym(h,"eglGetDisplay");EGLBoolean(*in)(EGLDisplay,EGLint*,EGLint*)=dlsym(h,"eglInitialize");EGLBoolean(*ba)(EGLenum)=dlsym(h,"eglBindAPI");EGLBoolean(*gc)(EGLDisplay,EGLConfig*,EGLint,EGLint*)=dlsym(h,"eglGetConfigs");EGLContext(*cc)(EGLDisplay,EGLConfig,EGLContext,const EGLint*)=dlsym(h,"eglCreateContext");EGLSurface(*cp)(EGLDisplay,EGLConfig,const EGLint*)=dlsym(h,"eglCreatePbufferSurface");EGLBoolean(*mc)(EGLDisplay,EGLSurface,EGLSurface,EGLContext)=dlsym(h,"eglMakeCurrent");EGLDisplay d=gd(EGL_DEFAULT_DISPLAY);EGLint x=0,y=0;CHECK(d!=EGL_NO_DISPLAY&&in(d,&x,&y),"EGL initialize");CHECK(ba(EGL_OPENGL_API),"EGL OpenGL API");EGLConfig c=0;EGLint n=0;CHECK(gc(d,&c,1,&n)&&n,"EGL config");const EGLint ca[]={EGL_CONTEXT_MAJOR_VERSION,4,EGL_CONTEXT_MINOR_VERSION,6,EGL_NONE},pa[]={EGL_WIDTH,W,EGL_HEIGHT,H,EGL_NONE};EGLContext q=cc(d,c,EGL_NO_CONTEXT,ca);EGLSurface s=cp(d,c,pa);CHECK(q!=EGL_NO_CONTEXT&&s!=EGL_NO_SURFACE&&mc(d,s,s,q),"EGL current");return q!=EGL_NO_CONTEXT&&s!=EGL_NO_SURFACE;}
static GLuint prog(A*a){const char*vs="#version 460 core\nvoid main(){uint id=uint(gl_VertexID);vec2 p=vec2(3.0);if(id==0xffffffffu)p=vec2(-0.78,-0.72);else if(id==3u)p=vec2(0.78,-0.72);else if(id==4u)p=vec2(0.0,0.76);gl_Position=vec4(p,0,1);}";const char*fs="#version 460 core\nout vec4 o;void main(){o=vec4(0,1,1,1);}";GLuint v=a->CreateShader(GL_VERTEX_SHADER),f=a->CreateShader(GL_FRAGMENT_SHADER);a->ShaderSource(v,1,&vs,0);a->ShaderSource(f,1,&fs,0);a->CompileShader(v);a->CompileShader(f);GLint x=0,y=0;a->GetShaderiv(v,GL_COMPILE_STATUS,&x);a->GetShaderiv(f,GL_COMPILE_STATUS,&y);if(!x||!y){char l[4096];GLsizei n=0;if(!x){a->GetShaderInfoLog(v,sizeof l,&n,l);fprintf(stderr,"VS %.*s\n",n,l);}if(!y){a->GetShaderInfoLog(f,sizeof l,&n,l);fprintf(stderr,"FS %.*s\n",n,l);}}CHECK(x&&y,"U32 max shaders compile");GLuint p=a->CreateProgram();a->AttachShader(p,v);a->AttachShader(p,f);a->LinkProgram(p);a->GetProgramiv(p,GL_LINK_STATUS,&x);if(!x){char l[4096];GLsizei n=0;a->GetProgramInfoLog(p,sizeof l,&n,l);fprintf(stderr,"LINK %.*s\n",n,l);}CHECK(x,"U32 max program links");return p;}
static GLuint fbo(A*a){GLuint t=0,f=0;a->GenTextures(1,&t);a->BindTexture(GL_TEXTURE_2D,t);a->TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST);a->TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST);a->TexImage2D(GL_TEXTURE_2D,0,GL_RGBA8,W,H,0,GL_RGBA,GL_UNSIGNED_BYTE,0);a->GenFramebuffers(1,&f);a->BindFramebuffer(GL_FRAMEBUFFER,f);a->FramebufferTexture2D(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_TEXTURE_2D,t,0);CHECK(a->CheckFramebufferStatus(GL_FRAMEBUFFER)==GL_FRAMEBUFFER_COMPLETE,"FBO complete");return f;}
static void clear(A*a,GLuint f,GLuint p){a->BindFramebuffer(GL_FRAMEBUFFER,f);a->Viewport(0,0,W,H);a->Disable(GL_PRIMITIVE_RESTART);a->Disable(GL_PRIMITIVE_RESTART_FIXED_INDEX);a->Disable(GL_DEPTH_TEST);a->Disable(GL_CULL_FACE);a->ClearColor(0,0,0,1);a->Clear(GL_COLOR_BUFFER_BIT);a->UseProgram(p);}
static unsigned cyan(A*a){uint8_t*p=malloc(W*H*4);a->Finish();a->ReadPixels(0,0,W,H,GL_RGBA,GL_UNSIGNED_BYTE,p);a->Finish();unsigned n=0;for(int i=0;i<W*H;i++)if(p[4*i]<80&&p[4*i+1]>150&&p[4*i+2]>150)n++;free(p);return n;}
static void upload(A*a,const uint32_t*ix,size_t n){GLuint va=0,e=0;a->GenVertexArrays(1,&va);a->BindVertexArray(va);a->GenBuffers(1,&e);a->BindBuffer(GL_ELEMENT_ARRAY_BUFFER,e);a->BufferData(GL_ELEMENT_ARRAY_BUFFER,(GLsizeiptr)(n*sizeof(*ix)),ix,GL_STATIC_DRAW);}
int main(int argc,char**argv){if(argc!=2)return 2;void*h=dlopen(argv[1],RTLD_NOW|RTLD_LOCAL);CHECK(h,"dlopen Mithril");if(!h)return 2;if(!eglsetup(h))return 1;A a;load(h,&a);GLuint f=fbo(&a),p=prog(&a);
 const uint32_t list[]={0xffffffffu,3u,4u};upload(&a,list,3);clear(&a,f,p);a.DrawElements(GL_TRIANGLES,3,GL_UNSIGNED_INT,0);CHECK(a.GetError()==GL_NO_ERROR,"U32 max triangle-list draw no error");unsigned nl=cyan(&a);CHECK(nl>1000,"U32 0xffffffff reaches vertex shader as ordinary list index (%u cyan)",nl);
 const uint32_t strip[]={0u,1u,2u,0xffffffffu,3u,4u};upload(&a,strip,6);clear(&a,f,p);a.DrawElements(GL_TRIANGLE_STRIP,6,GL_UNSIGNED_INT,0);CHECK(a.GetError()==GL_NO_ERROR,"U32 max disabled-restart triangle strip no error");unsigned ns=cyan(&a);CHECK(ns>1000,"U32 0xffffffff remains ordinary triangle-strip index when restart disabled (%u cyan)",ns);
 const uint32_t line[]={0xffffffffu,3u};upload(&a,line,2);clear(&a,f,p);a.DrawElements(GL_LINE_STRIP,2,GL_UNSIGNED_INT,0);CHECK(a.GetError()==GL_NO_ERROR,"U32 max disabled-restart line strip no error");unsigned nline=cyan(&a);CHECK(nline>40,"U32 0xffffffff remains ordinary line-strip index when restart disabled (%u cyan)",nline);
 const uint32_t custom[]={0xffffffffu,3u,4u,77u,0xffffffffu,3u,4u};upload(&a,custom,7);clear(&a,f,p);a.PrimitiveRestartIndex(77u);a.Enable(GL_PRIMITIVE_RESTART);a.DrawElements(GL_TRIANGLE_STRIP,7,GL_UNSIGNED_INT,0);CHECK(a.GetError()==GL_NO_ERROR,"U32 custom-restart/max-index strip no error");unsigned nc=cyan(&a);CHECK(nc>1000,"programmable restart token coexists with ordinary U32 max index (%u cyan)",nc);
 printf("U32_MAX_INDEX checks=%d failures=%d\n",checks,failures);return failures?1:0;}
