/* DirectMetal GL 3.3 raster-state oracle: MRT indexed color mask, blend, depth, polygon mode. */
#include <dlfcn.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <EGL/egl.h>
#include <GL/glcorearb.h>
#define W 64
#define H 64
static int checks=0,failures=0;
#define CHECK(c,fmt,...) do{++checks;if(c)printf("ok  : " fmt "\n",##__VA_ARGS__);else{printf("FAIL: " fmt "\n",##__VA_ARGS__);++failures;}}while(0)
typedef struct A{const GLubyte*(*GetString)(GLenum);GLenum(*GetError)(void);void(*Finish)(void);void(*Viewport)(GLint,GLint,GLsizei,GLsizei);void(*ClearColor)(GLfloat,GLfloat,GLfloat,GLfloat);void(*ClearDepth)(GLdouble);void(*Clear)(GLbitfield);void(*ReadPixels)(GLint,GLint,GLsizei,GLsizei,GLenum,GLenum,void*);void(*Enable)(GLenum);void(*Disable)(GLenum);void(*BlendFuncSeparate)(GLenum,GLenum,GLenum,GLenum);void(*DepthFunc)(GLenum);void(*DepthMask)(GLboolean);void(*PolygonMode)(GLenum,GLenum);void(*ColorMask)(GLboolean,GLboolean,GLboolean,GLboolean);void(*ColorMaski)(GLuint,GLboolean,GLboolean,GLboolean,GLboolean);void(*GenTextures)(GLsizei,GLuint*);void(*BindTexture)(GLenum,GLuint);void(*TexImage2D)(GLenum,GLint,GLint,GLsizei,GLsizei,GLint,GLenum,GLenum,const void*);void(*TexParameteri)(GLenum,GLenum,GLint);void(*GenFramebuffers)(GLsizei,GLuint*);void(*BindFramebuffer)(GLenum,GLuint);void(*FramebufferTexture2D)(GLenum,GLenum,GLenum,GLuint,GLint);GLenum(*CheckFramebufferStatus)(GLenum);void(*DrawBuffers)(GLsizei,const GLenum*);void(*DrawBuffer)(GLenum);void(*ReadBuffer)(GLenum);GLuint(*CreateShader)(GLenum);void(*ShaderSource)(GLuint,GLsizei,const GLchar*const*,const GLint*);void(*CompileShader)(GLuint);void(*GetShaderiv)(GLuint,GLenum,GLint*);GLuint(*CreateProgram)(void);void(*AttachShader)(GLuint,GLuint);void(*LinkProgram)(GLuint);void(*GetProgramiv)(GLuint,GLenum,GLint*);void(*UseProgram)(GLuint);GLint(*GetUniformLocation)(GLuint,const GLchar*);void(*Uniform4f)(GLint,GLfloat,GLfloat,GLfloat,GLfloat);void(*Uniform1f)(GLint,GLfloat);void(*GenVertexArrays)(GLsizei,GLuint*);void(*BindVertexArray)(GLuint);void(*DrawArrays)(GLenum,GLint,GLsizei);}A;
#define L(a,h,f) do{(a)->f=(__typeof__((a)->f))dlsym((h),"gl"#f);CHECK((a)->f!=NULL,"resolve gl%s",#f);}while(0)
static int load(void*h,A*a){memset(a,0,sizeof(*a));L(a,h,GetString);L(a,h,GetError);L(a,h,Finish);L(a,h,Viewport);L(a,h,ClearColor);L(a,h,ClearDepth);L(a,h,Clear);L(a,h,ReadPixels);L(a,h,Enable);L(a,h,Disable);L(a,h,BlendFuncSeparate);L(a,h,DepthFunc);L(a,h,DepthMask);L(a,h,PolygonMode);L(a,h,ColorMask);L(a,h,ColorMaski);L(a,h,GenTextures);L(a,h,BindTexture);L(a,h,TexImage2D);L(a,h,TexParameteri);L(a,h,GenFramebuffers);L(a,h,BindFramebuffer);L(a,h,FramebufferTexture2D);L(a,h,CheckFramebufferStatus);L(a,h,DrawBuffers);L(a,h,DrawBuffer);L(a,h,ReadBuffer);L(a,h,CreateShader);L(a,h,ShaderSource);L(a,h,CompileShader);L(a,h,GetShaderiv);L(a,h,CreateProgram);L(a,h,AttachShader);L(a,h,LinkProgram);L(a,h,GetProgramiv);L(a,h,UseProgram);L(a,h,GetUniformLocation);L(a,h,Uniform4f);L(a,h,Uniform1f);L(a,h,GenVertexArrays);L(a,h,BindVertexArray);L(a,h,DrawArrays);return failures==0;}
#undef L
static int egl(void*h){EGLDisplay(*gd)(EGLNativeDisplayType)=dlsym(h,"eglGetDisplay");EGLBoolean(*init)(EGLDisplay,EGLint*,EGLint*)=dlsym(h,"eglInitialize");EGLBoolean(*ba)(EGLenum)=dlsym(h,"eglBindAPI");EGLBoolean(*gc)(EGLDisplay,EGLConfig*,EGLint,EGLint*)=dlsym(h,"eglGetConfigs");EGLContext(*cc)(EGLDisplay,EGLConfig,EGLContext,const EGLint*)=dlsym(h,"eglCreateContext");EGLSurface(*ps)(EGLDisplay,EGLConfig,const EGLint*)=dlsym(h,"eglCreatePbufferSurface");EGLBoolean(*mc)(EGLDisplay,EGLSurface,EGLSurface,EGLContext)=dlsym(h,"eglMakeCurrent");CHECK(gd&&init&&ba&&gc&&cc&&ps&&mc,"resolve EGL");if(!gd||!init||!ba||!gc||!cc||!ps||!mc)return 0;EGLDisplay d=gd(EGL_DEFAULT_DISPLAY);EGLint x=0,y=0;CHECK(d!=EGL_NO_DISPLAY&&init(d,&x,&y),"init EGL");CHECK(ba(EGL_OPENGL_API),"bind API");EGLConfig c=0;EGLint n=0;CHECK(gc(d,&c,1,&n)&&n>0,"config");const EGLint ca[]={EGL_CONTEXT_MAJOR_VERSION,3,EGL_CONTEXT_MINOR_VERSION,3,EGL_NONE},pa[]={EGL_WIDTH,W,EGL_HEIGHT,H,EGL_NONE};EGLContext cx=cc(d,c,EGL_NO_CONTEXT,ca);EGLSurface s=ps(d,c,pa);CHECK(cx!=EGL_NO_CONTEXT&&s!=EGL_NO_SURFACE,"context/pbuffer");CHECK(mc(d,s,s,cx),"make current");return cx!=EGL_NO_CONTEXT&&s!=EGL_NO_SURFACE;}
static GLuint prog(A*a){const char*vs="#version 330 core\nuniform float z;void main(){const vec2 p[3]=vec2[3](vec2(-0.8,-0.8),vec2(0.8,-0.8),vec2(0.0,0.8));gl_Position=vec4(p[gl_VertexID],z,1);}\n";const char*fs="#version 330 core\nuniform vec4 c0;uniform vec4 c1;layout(location=0)out vec4 o0;layout(location=1)out vec4 o1;void main(){o0=c0;o1=c1;}\n";GLuint s0=a->CreateShader(GL_VERTEX_SHADER),s1=a->CreateShader(GL_FRAGMENT_SHADER);a->ShaderSource(s0,1,&vs,0);a->ShaderSource(s1,1,&fs,0);a->CompileShader(s0);a->CompileShader(s1);GLint q0=0,q1=0;a->GetShaderiv(s0,GL_COMPILE_STATUS,&q0);a->GetShaderiv(s1,GL_COMPILE_STATUS,&q1);CHECK(q0&&q1,"raster shaders compile");GLuint p=a->CreateProgram();a->AttachShader(p,s0);a->AttachShader(p,s1);a->LinkProgram(p);GLint q=0;a->GetProgramiv(p,GL_LINK_STATUS,&q);CHECK(q,"raster program links");return p;}
static GLuint tex(A*a,GLint internal,GLenum fmt,GLenum type){GLuint t=0;a->GenTextures(1,&t);a->BindTexture(GL_TEXTURE_2D,t);a->TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST);a->TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST);a->TexImage2D(GL_TEXTURE_2D,0,internal,W,H,0,fmt,type,0);return t;}
static void readc(A*a,GLenum rb,uint8_t p[4]){a->ReadBuffer(rb);a->Finish();a->ReadPixels(W/2,H/2,1,1,GL_RGBA,GL_UNSIGNED_BYTE,p);a->Finish();}
static int near4(const uint8_t*p,int r,int g,int b,int tol){return abs((int)p[0]-r)<=tol&&abs((int)p[1]-g)<=tol&&abs((int)p[2]-b)<=tol&&p[3]>240;}
int main(int ac,char**av){const char*path=ac>1?av[1]:"./libmithril.dylib";void*h=dlopen(path,RTLD_NOW|RTLD_GLOBAL);CHECK(h!=0,"dlopen %s",path);if(!h)return 2;if(!egl(h))return 2;A a;if(!load(h,&a))return 2;const char*v=(const char*)a.GetString(GL_VERSION);CHECK(v&&strstr(v,"3.3.0")&&strstr(v,"DirectMetal"),"DirectMetal 3.3 active (%s)",v?v:"null");while(a.GetError()!=GL_NO_ERROR){}GLuint c0=tex(&a,GL_RGBA8,GL_RGBA,GL_UNSIGNED_BYTE),c1=tex(&a,GL_RGBA8,GL_RGBA,GL_UNSIGNED_BYTE),d=tex(&a,GL_DEPTH_COMPONENT32F,GL_DEPTH_COMPONENT,GL_FLOAT),f=0;a.GenFramebuffers(1,&f);a.BindFramebuffer(GL_FRAMEBUFFER,f);a.FramebufferTexture2D(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_TEXTURE_2D,c0,0);a.FramebufferTexture2D(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT1,GL_TEXTURE_2D,c1,0);a.FramebufferTexture2D(GL_FRAMEBUFFER,GL_DEPTH_ATTACHMENT,GL_TEXTURE_2D,d,0);GLenum bufs[2]={GL_COLOR_ATTACHMENT0,GL_COLOR_ATTACHMENT1};a.DrawBuffers(2,bufs);CHECK(a.CheckFramebufferStatus(GL_FRAMEBUFFER)==GL_FRAMEBUFFER_COMPLETE,"MRT+depth FBO complete");GLuint p=prog(&a),vao=0;a.GenVertexArrays(1,&vao);a.BindVertexArray(vao);a.UseProgram(p);GLint l0=a.GetUniformLocation(p,"c0"),l1=a.GetUniformLocation(p,"c1"),lz=a.GetUniformLocation(p,"z");CHECK(l0>=0&&l1>=0&&lz>=0,"uniform locations");a.Viewport(0,0,W,H);
 /* Indexed color masks must differ per attachment. */a.Disable(GL_BLEND);a.Disable(GL_DEPTH_TEST);a.PolygonMode(GL_FRONT_AND_BACK,GL_FILL);a.ColorMask(GL_TRUE,GL_TRUE,GL_TRUE,GL_TRUE);a.ClearColor(0,0,0,1);a.Clear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);a.ColorMaski(0,GL_TRUE,GL_FALSE,GL_FALSE,GL_TRUE);a.ColorMaski(1,GL_FALSE,GL_TRUE,GL_FALSE,GL_TRUE);a.Uniform4f(l0,1,1,1,1);a.Uniform4f(l1,1,1,1,1);a.Uniform1f(lz,0);a.DrawArrays(GL_TRIANGLES,0,3);uint8_t x0[4]={0},x1[4]={0};readc(&a,GL_COLOR_ATTACHMENT0,x0);readc(&a,GL_COLOR_ATTACHMENT1,x1);CHECK(near4(x0,255,0,0,5),"ColorMaski attachment0 writes red only (%u,%u,%u,%u)",x0[0],x0[1],x0[2],x0[3]);CHECK(near4(x1,0,255,0,5),"ColorMaski attachment1 writes green only (%u,%u,%u,%u)",x1[0],x1[1],x1[2],x1[3]);
 /* Blend equation/factors. */a.DrawBuffer(GL_COLOR_ATTACHMENT0);a.ColorMask(GL_TRUE,GL_TRUE,GL_TRUE,GL_TRUE);a.ClearColor(0,0,1,1);a.Clear(GL_COLOR_BUFFER_BIT);a.Enable(GL_BLEND);a.BlendFuncSeparate(GL_SRC_ALPHA,GL_ONE_MINUS_SRC_ALPHA,GL_ONE,GL_ZERO);a.Uniform4f(l0,1,0,0,0.5f);a.DrawArrays(GL_TRIANGLES,0,3);readc(&a,GL_COLOR_ATTACHMENT0,x0);CHECK(abs((int)x0[0]-128)<=8&&x0[1]<8&&abs((int)x0[2]-128)<=8&&abs((int)x0[3]-128)<=8,"SRC_ALPHA blend red over blue -> purple with source alpha (%u,%u,%u,%u)",x0[0],x0[1],x0[2],x0[3]);a.Disable(GL_BLEND);
 /* Depth compare/write: near red writes depth, farther green must fail LESS. */a.Enable(GL_DEPTH_TEST);a.DepthFunc(GL_LESS);a.DepthMask(GL_TRUE);a.ClearColor(0,0,0,1);a.ClearDepth(1.0);a.Clear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);a.Uniform4f(l0,1,0,0,1);a.Uniform1f(lz,-0.5f);a.DrawArrays(GL_TRIANGLES,0,3);a.Uniform4f(l0,0,1,0,1);a.Uniform1f(lz,0.5f);a.DrawArrays(GL_TRIANGLES,0,3);readc(&a,GL_COLOR_ATTACHMENT0,x0);CHECK(near4(x0,255,0,0,5),"depth LESS rejects farther green after near red (%u,%u,%u,%u)",x0[0],x0[1],x0[2],x0[3]);a.Disable(GL_DEPTH_TEST);
 /* Polygon line mode must not fill triangle center. */a.ClearColor(0,0,0,1);a.Clear(GL_COLOR_BUFFER_BIT);a.PolygonMode(GL_FRONT_AND_BACK,GL_LINE);a.Uniform4f(l0,1,0,0,1);a.Uniform1f(lz,0);a.DrawArrays(GL_TRIANGLES,0,3);readc(&a,GL_COLOR_ATTACHMENT0,x0);CHECK(near4(x0,0,0,0,5),"polygon line mode leaves triangle center unfilled (%u,%u,%u,%u)",x0[0],x0[1],x0[2],x0[3]);a.PolygonMode(GL_FRONT_AND_BACK,GL_FILL);CHECK(a.GetError()==GL_NO_ERROR,"raster oracle ends without GL error");printf("RASTER SEMANTICS SMOKE: %d checks, %d failure(s)\n",checks,failures);if(!failures)printf("RASTER SEMANTICS SMOKE ALL PASSED\n");return failures?1:0;}
