#!/usr/bin/env python3
from pathlib import Path
p = Path('Mithril-Wrapper-cpp/MG_Backend/DirectVulkan/Resources.cpp')
s = p.read_text()
old_sig = '''void stage_and_copy_image(TextureEntry& tex, int level, int x, int y, int z,\n                          int w, int h, int d, const void* pixels,\n                          int unpack_alignment, GLenum format, GLenum type,\n                          bool is_full_upload) {\n'''
new_sig = '''void stage_and_copy_image(TextureEntry& tex, int level, int x, int y, int z,\n                          int w, int h, int d, const void* pixels,\n                          const MGUnpackParams* unpack, GLenum format, GLenum type,\n                          bool is_full_upload) {\n'''
assert s.count(old_sig) == 1, s.count(old_sig)
s = s.replace(old_sig, new_sig, 1)
old_init = '''    if (!ensure_command_buffer_recording()) return;\n    if (unpack_alignment <= 0) unpack_alignment = 4;  // GL default UNPACK_ALIGNMENT\n\n    // Compute host-side bytes per pixel for this (format, type) pair and\n'''
new_init = '''    if (!ensure_command_buffer_recording()) return;\n    int unpack_alignment = (unpack && unpack->unpackAlignment > 0)\n                               ? unpack->unpackAlignment : 4;\n    const int unpack_row_length = (unpack && unpack->unpackRowLength > 0)\n                                      ? unpack->unpackRowLength : w;\n    const int unpack_image_height = (unpack && unpack->unpackImageHeight > 0)\n                                        ? unpack->unpackImageHeight : h;\n    const int unpack_skip_pixels = (unpack && unpack->unpackSkipPixels > 0)\n                                       ? unpack->unpackSkipPixels : 0;\n    const int unpack_skip_rows = (unpack && unpack->unpackSkipRows > 0)\n                                     ? unpack->unpackSkipRows : 0;\n    const int unpack_skip_images = (unpack && unpack->unpackSkipImages > 0)\n                                       ? unpack->unpackSkipImages : 0;\n\n    // Compute host-side bytes per pixel for this (format, type) pair and\n'''
assert s.count(old_init) == 1, s.count(old_init)
s = s.replace(old_init, new_init, 1)
old_stride = '''    size_t mask = (size_t)unpack_alignment - 1;\n    // staging 装的是展开后的 RGBA 数据（紧密排列）；tight_row 按 dst_bpp 计算。\n    // 源行 stride 按 src_bpp 计算并受 GL_UNPACK_ALIGNMENT 约束。\n    // 非展开路径下 src_bpp == dst_bpp == bpp，行为与原实现完全一致。\n    size_t tight_row = (size_t)w * (size_t)dst_bpp;\n    size_t src_tight_row = (size_t)w * (size_t)src_bpp;\n    size_t src_stride = (src_tight_row + mask) & ~mask;\n    size_t staging = tight_row * (size_t)h * (size_t)d;\n'''
new_stride = '''    size_t mask = (size_t)unpack_alignment - 1;\n    // Destination staging is tightly packed. Source addressing must honor the\n    // complete OpenGL pixel-unpack state, not just UNPACK_ALIGNMENT. Minecraft\n    // atlas uploads routinely use ROW_LENGTH + SKIP_PIXELS/SKIP_ROWS.\n    size_t tight_row = (size_t)w * (size_t)dst_bpp;\n    size_t src_tight_row = (size_t)unpack_row_length * (size_t)src_bpp;\n    size_t src_stride = (src_tight_row + mask) & ~mask;\n    size_t src_image_stride = src_stride * (size_t)unpack_image_height;\n    size_t src_base_offset = (size_t)unpack_skip_images * src_image_stride\n                           + (size_t)unpack_skip_rows * src_stride\n                           + (size_t)unpack_skip_pixels * (size_t)src_bpp;\n    const char* src_base = (const char*)pixels + src_base_offset;\n    size_t staging = tight_row * (size_t)h * (size_t)d;\n'''
assert s.count(old_stride) == 1, s.count(old_stride)
s = s.replace(old_stride, new_stride, 1)
old_expand_start = '''            const int alpha_bytes = src_bpp / 3;  // 每分量字节数: 1/2/4\n            const char* s8 = (const char*)pixels;\n            for (int layer = 0; layer < d; ++layer) {\n                for (int row = 0; row < h; ++row) {\n                    const char* src_row = s8;\n'''
new_expand_start = '''            const int alpha_bytes = src_bpp / 3;  // 每分量字节数: 1/2/4\n            for (int layer = 0; layer < d; ++layer) {\n                const char* layer_src = src_base + (size_t)layer * src_image_stride;\n                for (int row = 0; row < h; ++row) {\n                    const char* src_row = layer_src + (size_t)row * src_stride;\n'''
assert s.count(old_expand_start) == 1, s.count(old_expand_start)
s = s.replace(old_expand_start, new_expand_start, 1)
old_expand_end = '''                    }\n                    s8 += src_stride;  // 源行按 GL_UNPACK_ALIGNMENT stride\n                }\n            }\n        } else if (src_stride == tight_row) {\n            // Source rows are already tightly packed — single memcpy.\n            std::memcpy(dst, pixels, staging);\n        } else {\n            // Source rows carry GL_UNPACK_ALIGNMENT padding; repack to tight\n            // so VkBufferImageCopy.bufferRowLength == 0 (== w) is valid.\n            const char* s8 = (const char*)pixels;\n            for (int layer = 0; layer < d; ++layer) {\n                for (int row = 0; row < h; ++row) {\n                    std::memcpy(dst, s8, tight_row);\n                    dst += tight_row;\n                    s8 += src_stride;\n                }\n            }\n        }\n'''
new_expand_end = '''                    }\n                }\n            }\n        } else if (src_base_offset == 0 && src_stride == tight_row &&\n                   src_image_stride == tight_row * (size_t)h) {\n            // Source rows/layers are already tightly packed — single memcpy.\n            std::memcpy(dst, src_base, staging);\n        } else {\n            // Repack the requested sub-rectangle/layers into tight staging.\n            for (int layer = 0; layer < d; ++layer) {\n                const char* layer_src = src_base + (size_t)layer * src_image_stride;\n                for (int row = 0; row < h; ++row) {\n                    const char* src_row = layer_src + (size_t)row * src_stride;\n                    std::memcpy(dst, src_row, tight_row);\n                    dst += tight_row;\n                }\n            }\n        }\n'''
assert s.count(old_expand_end) == 1, s.count(old_expand_end)
s = s.replace(old_expand_end, new_expand_end, 1)
old_call = '''    const int unpack_alignment = (unpack && unpack->unpackAlignment > 0)\n                                     ? unpack->unpackAlignment : 4;\n    mithril::vk::stage_and_copy_image(it->second, level, x, y, z, w, h, d,\n                                      pixels, unpack_alignment, format, type,\n                                      is_full_upload != 0);\n'''
new_call = '''    mithril::vk::stage_and_copy_image(it->second, level, x, y, z, w, h, d,\n                                      pixels, unpack, format, type,\n                                      is_full_upload != 0);\n'''
assert s.count(old_call) == 1, s.count(old_call)
s = s.replace(old_call, new_call, 1)
p.write_text(s)
