#!/usr/bin/env python3
from pathlib import Path
p = Path('Mithril-Wrapper-cpp/MG_Backend/DirectVulkan/ImageOps.cpp')
s = p.read_text()
old = '''    int dst_bpp = host_texel_bytes(format, type);\n    if (dst_bpp <= 0) dst_bpp = 4;\n\n    if (src_bpp == dst_bpp) {\n        std::memcpy(out_pixels, mapped, (size_t)staging_size);\n    } else {\n        // Best-effort: copy byte-for-byte up to the smaller of the two sizes.\n        size_t n = std::min((size_t)staging_size, (size_t)w * h * dst_bpp);\n        std::memcpy(out_pixels, mapped, n);\n    }\n'''
new = '''    int dst_bpp = host_texel_bytes(format, type);\n    if (dst_bpp <= 0) dst_bpp = 4;\n\n    // vkCmdCopyImageToBuffer preserves the image format's byte/component\n    // layout. The default macOS swapchain is normally B8G8R8A8_UNORM, while\n    // OpenGL glReadPixels(GL_RGBA, GL_UNSIGNED_BYTE, ...) promises RGBA bytes\n    // independently of the framebuffer's internal storage format. A raw memcpy\n    // therefore exposes BGRA memory as RGBA and swaps red/blue in screenshots\n    // and readback-based conformance tests. Convert the two common 8-bit\n    // four-component layouts explicitly; keep identical-layout reads memcpy-fast.\n    const bool src_bgra8 =\n        src_fmt == VK_FORMAT_B8G8R8A8_UNORM ||\n        src_fmt == VK_FORMAT_B8G8R8A8_SRGB;\n    const bool src_rgba8 =\n        src_fmt == VK_FORMAT_R8G8B8A8_UNORM ||\n        src_fmt == VK_FORMAT_R8G8B8A8_SRGB;\n    const bool dst_rgba8 = format == GL_RGBA && type == GL_UNSIGNED_BYTE;\n    const bool dst_bgra8 = format == GL_BGRA && type == GL_UNSIGNED_BYTE;\n\n    if (src_bpp == 4 && dst_bpp == 4 &&\n        ((src_bgra8 && dst_rgba8) || (src_rgba8 && dst_bgra8))) {\n        const uint8_t* src = static_cast<const uint8_t*>(mapped);\n        uint8_t* dst = static_cast<uint8_t*>(out_pixels);\n        const size_t count = (size_t)w * (size_t)h;\n        for (size_t i = 0; i < count; ++i) {\n            dst[i * 4 + 0] = src[i * 4 + 2];\n            dst[i * 4 + 1] = src[i * 4 + 1];\n            dst[i * 4 + 2] = src[i * 4 + 0];\n            dst[i * 4 + 3] = src[i * 4 + 3];\n        }\n    } else if (src_bpp == dst_bpp) {\n        std::memcpy(out_pixels, mapped, (size_t)staging_size);\n    } else {\n        // Best-effort: copy byte-for-byte up to the smaller of the two sizes.\n        size_t n = std::min((size_t)staging_size, (size_t)w * h * dst_bpp);\n        std::memcpy(out_pixels, mapped, n);\n    }\n'''
assert s.count(old) == 1, s.count(old)
s = s.replace(old, new, 1)
# Ensure byte-count selection recognizes BGRA sRGB as a four-byte format too.
old_case = '''        case VK_FORMAT_B8G8R8A8_UNORM:\n        case VK_FORMAT_R8G8B8A8_UNORM:\n        case VK_FORMAT_R8G8B8A8_SRGB: src_bpp = 4; break;\n'''
new_case = '''        case VK_FORMAT_B8G8R8A8_UNORM:\n        case VK_FORMAT_B8G8R8A8_SRGB:\n        case VK_FORMAT_R8G8B8A8_UNORM:\n        case VK_FORMAT_R8G8B8A8_SRGB: src_bpp = 4; break;\n'''
assert s.count(old_case) == 1, s.count(old_case)
s = s.replace(old_case, new_case, 1)
p.write_text(s)
