// Mithril-Wrapper GL entry points -- stub table.
// GENERATED by scripts/gen_gl_stubs.py -- DO NOT EDIT BY HAND.
#include <GL/glcorearb.h>

namespace mithril {
void GlStubCalled(const char* name);
} // namespace mithril

extern "C" {

  void APIENTRY glBeginConditionalRender(GLuint id, GLenum mode) {
    mithril::GlStubCalled("glBeginConditionalRender");
  }

  void APIENTRY glBeginQuery(GLenum target, GLuint id) {
    mithril::GlStubCalled("glBeginQuery");
  }

  void APIENTRY glBeginTransformFeedback(GLenum primitiveMode) {
    mithril::GlStubCalled("glBeginTransformFeedback");
  }

  void APIENTRY glBindFragDataLocation(GLuint program, GLuint color, const GLchar *name) {
    mithril::GlStubCalled("glBindFragDataLocation");
  }

  void APIENTRY glBindFragDataLocationIndexed(GLuint program, GLuint colorNumber, GLuint index, const GLchar *name) {
    mithril::GlStubCalled("glBindFragDataLocationIndexed");
  }

  GLenum APIENTRY glClientWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout) {
    mithril::GlStubCalled("glClientWaitSync");
    return 0;
  }

  void APIENTRY glDeleteQueries(GLsizei n, const GLuint *ids) {
    mithril::GlStubCalled("glDeleteQueries");
  }

  void APIENTRY glDeleteSync(GLsync sync) {
    mithril::GlStubCalled("glDeleteSync");
  }

  void APIENTRY glEndConditionalRender(void) {
    mithril::GlStubCalled("glEndConditionalRender");
  }

  void APIENTRY glEndQuery(GLenum target) {
    mithril::GlStubCalled("glEndQuery");
  }

  void APIENTRY glEndTransformFeedback(void) {
    mithril::GlStubCalled("glEndTransformFeedback");
  }

  GLsync APIENTRY glFenceSync(GLenum condition, GLbitfield flags) {
    mithril::GlStubCalled("glFenceSync");
    return nullptr;
  }

  void APIENTRY glGenQueries(GLsizei n, GLuint *ids) {
    mithril::GlStubCalled("glGenQueries");
  }

  GLint APIENTRY glGetFragDataIndex(GLuint program, const GLchar *name) {
    mithril::GlStubCalled("glGetFragDataIndex");
    return 0;
  }

  GLint APIENTRY glGetFragDataLocation(GLuint program, const GLchar *name) {
    mithril::GlStubCalled("glGetFragDataLocation");
    return 0;
  }

  void APIENTRY glGetMultisamplefv(GLenum pname, GLuint index, GLfloat *val) {
    mithril::GlStubCalled("glGetMultisamplefv");
  }

  void APIENTRY glGetQueryObjecti64v(GLuint id, GLenum pname, GLint64 *params) {
    mithril::GlStubCalled("glGetQueryObjecti64v");
  }

  void APIENTRY glGetQueryObjectiv(GLuint id, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetQueryObjectiv");
  }

  void APIENTRY glGetQueryObjectui64v(GLuint id, GLenum pname, GLuint64 *params) {
    mithril::GlStubCalled("glGetQueryObjectui64v");
  }

  void APIENTRY glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint *params) {
    mithril::GlStubCalled("glGetQueryObjectuiv");
  }

  void APIENTRY glGetQueryiv(GLenum target, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetQueryiv");
  }

  void APIENTRY glGetSynciv(GLsync sync, GLenum pname, GLsizei count, GLsizei *length, GLint *values) {
    mithril::GlStubCalled("glGetSynciv");
  }

  void APIENTRY glGetTransformFeedbackVarying(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name) {
    mithril::GlStubCalled("glGetTransformFeedbackVarying");
  }

  GLboolean APIENTRY glIsQuery(GLuint id) {
    mithril::GlStubCalled("glIsQuery");
    return 0;
  }

  GLboolean APIENTRY glIsSync(GLsync sync) {
    mithril::GlStubCalled("glIsSync");
    return 0;
  }

  void APIENTRY glPointParameterf(GLenum pname, GLfloat param) {
    mithril::GlStubCalled("glPointParameterf");
  }

  void APIENTRY glPointParameterfv(GLenum pname, const GLfloat *params) {
    mithril::GlStubCalled("glPointParameterfv");
  }

  void APIENTRY glPointParameteri(GLenum pname, GLint param) {
    mithril::GlStubCalled("glPointParameteri");
  }

  void APIENTRY glPointParameteriv(GLenum pname, const GLint *params) {
    mithril::GlStubCalled("glPointParameteriv");
  }

  void APIENTRY glPrimitiveRestartIndex(GLuint index) {
    mithril::GlStubCalled("glPrimitiveRestartIndex");
  }

  void APIENTRY glProvokingVertex(GLenum mode) {
    mithril::GlStubCalled("glProvokingVertex");
  }

  void APIENTRY glQueryCounter(GLuint id, GLenum target) {
    mithril::GlStubCalled("glQueryCounter");
  }

  void APIENTRY glTexImage2DMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations) {
    mithril::GlStubCalled("glTexImage2DMultisample");
  }

  void APIENTRY glTexImage3DMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations) {
    mithril::GlStubCalled("glTexImage3DMultisample");
  }

  void APIENTRY glTransformFeedbackVaryings(GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode) {
    mithril::GlStubCalled("glTransformFeedbackVaryings");
  }

  void APIENTRY glVertexAttribI1i(GLuint index, GLint x) {
    mithril::GlStubCalled("glVertexAttribI1i");
  }

  void APIENTRY glVertexAttribI1iv(GLuint index, const GLint *v) {
    mithril::GlStubCalled("glVertexAttribI1iv");
  }

  void APIENTRY glVertexAttribI1ui(GLuint index, GLuint x) {
    mithril::GlStubCalled("glVertexAttribI1ui");
  }

  void APIENTRY glVertexAttribI1uiv(GLuint index, const GLuint *v) {
    mithril::GlStubCalled("glVertexAttribI1uiv");
  }

  void APIENTRY glVertexAttribI2i(GLuint index, GLint x, GLint y) {
    mithril::GlStubCalled("glVertexAttribI2i");
  }

  void APIENTRY glVertexAttribI2iv(GLuint index, const GLint *v) {
    mithril::GlStubCalled("glVertexAttribI2iv");
  }

  void APIENTRY glVertexAttribI2ui(GLuint index, GLuint x, GLuint y) {
    mithril::GlStubCalled("glVertexAttribI2ui");
  }

  void APIENTRY glVertexAttribI2uiv(GLuint index, const GLuint *v) {
    mithril::GlStubCalled("glVertexAttribI2uiv");
  }

  void APIENTRY glVertexAttribI3i(GLuint index, GLint x, GLint y, GLint z) {
    mithril::GlStubCalled("glVertexAttribI3i");
  }

  void APIENTRY glVertexAttribI3iv(GLuint index, const GLint *v) {
    mithril::GlStubCalled("glVertexAttribI3iv");
  }

  void APIENTRY glVertexAttribI3ui(GLuint index, GLuint x, GLuint y, GLuint z) {
    mithril::GlStubCalled("glVertexAttribI3ui");
  }

  void APIENTRY glVertexAttribI3uiv(GLuint index, const GLuint *v) {
    mithril::GlStubCalled("glVertexAttribI3uiv");
  }

  void APIENTRY glVertexAttribI4bv(GLuint index, const GLbyte *v) {
    mithril::GlStubCalled("glVertexAttribI4bv");
  }

  void APIENTRY glVertexAttribI4i(GLuint index, GLint x, GLint y, GLint z, GLint w) {
    mithril::GlStubCalled("glVertexAttribI4i");
  }

  void APIENTRY glVertexAttribI4iv(GLuint index, const GLint *v) {
    mithril::GlStubCalled("glVertexAttribI4iv");
  }

  void APIENTRY glVertexAttribI4sv(GLuint index, const GLshort *v) {
    mithril::GlStubCalled("glVertexAttribI4sv");
  }

  void APIENTRY glVertexAttribI4ubv(GLuint index, const GLubyte *v) {
    mithril::GlStubCalled("glVertexAttribI4ubv");
  }

  void APIENTRY glVertexAttribI4ui(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w) {
    mithril::GlStubCalled("glVertexAttribI4ui");
  }

  void APIENTRY glVertexAttribI4uiv(GLuint index, const GLuint *v) {
    mithril::GlStubCalled("glVertexAttribI4uiv");
  }

  void APIENTRY glVertexAttribI4usv(GLuint index, const GLushort *v) {
    mithril::GlStubCalled("glVertexAttribI4usv");
  }

  void APIENTRY glVertexAttribP1ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP1ui");
  }

  void APIENTRY glVertexAttribP1uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP1uiv");
  }

  void APIENTRY glVertexAttribP2ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP2ui");
  }

  void APIENTRY glVertexAttribP2uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP2uiv");
  }

  void APIENTRY glVertexAttribP3ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP3ui");
  }

  void APIENTRY glVertexAttribP3uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP3uiv");
  }

  void APIENTRY glVertexAttribP4ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP4ui");
  }

  void APIENTRY glVertexAttribP4uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP4uiv");
  }

  void APIENTRY glWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout) {
    mithril::GlStubCalled("glWaitSync");
  }

} // extern "C"
