// Mithril-Wrapper GL entry points -- stub table.
// GENERATED by scripts/gen_gl_stubs.py -- DO NOT EDIT BY HAND.
#include <GL/glcorearb.h>

namespace mithril {
void GlStubCalled(const char* name);
} // namespace mithril

extern "C" {

  void APIENTRY glBeginTransformFeedback(GLenum primitiveMode) {
    mithril::GlStubCalled("glBeginTransformFeedback");
  }

  void APIENTRY glEndTransformFeedback(void) {
    mithril::GlStubCalled("glEndTransformFeedback");
  }

  void APIENTRY glGetMultisamplefv(GLenum pname, GLuint index, GLfloat *val) {
    mithril::GlStubCalled("glGetMultisamplefv");
  }

  void APIENTRY glGetTransformFeedbackVarying(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name) {
    mithril::GlStubCalled("glGetTransformFeedbackVarying");
  }

  void APIENTRY glPointParameterf(GLenum pname, GLfloat param) {
    mithril::GlStubCalled("glPointParameterf");
  }

  void APIENTRY glPointParameterfv(GLenum pname, const GLfloat *params) {
    mithril::GlStubCalled("glPointParameterfv");
  }

  void APIENTRY glPointParameteri(GLenum pname, GLint param) {
    mithril::GlStubCalled("glPointParameteri");
  }

  void APIENTRY glPointParameteriv(GLenum pname, const GLint *params) {
    mithril::GlStubCalled("glPointParameteriv");
  }

  void APIENTRY glTexImage3DMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations) {
    mithril::GlStubCalled("glTexImage3DMultisample");
  }

  void APIENTRY glTransformFeedbackVaryings(GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode) {
    mithril::GlStubCalled("glTransformFeedbackVaryings");
  }

  void APIENTRY glVertexAttribP1ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP1ui");
  }

  void APIENTRY glVertexAttribP1uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP1uiv");
  }

  void APIENTRY glVertexAttribP2ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP2ui");
  }

  void APIENTRY glVertexAttribP2uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP2uiv");
  }

  void APIENTRY glVertexAttribP3ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP3ui");
  }

  void APIENTRY glVertexAttribP3uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP3uiv");
  }

  void APIENTRY glVertexAttribP4ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP4ui");
  }

  void APIENTRY glVertexAttribP4uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP4uiv");
  }

} // extern "C"
