// Mithril-Wrapper GL entry points -- stub table.
// GENERATED by scripts/gen_gl_stubs.py -- DO NOT EDIT BY HAND.
#include <GL/glcorearb.h>

namespace mithril {
void GlStubCalled(const char* name);
} // namespace mithril

extern "C" {

  void APIENTRY glActiveTexture(GLenum texture) {
    mithril::GlStubCalled("glActiveTexture");
  }

  void APIENTRY glAttachShader(GLuint program, GLuint shader) {
    mithril::GlStubCalled("glAttachShader");
  }

  void APIENTRY glBeginConditionalRender(GLuint id, GLenum mode) {
    mithril::GlStubCalled("glBeginConditionalRender");
  }

  void APIENTRY glBeginQuery(GLenum target, GLuint id) {
    mithril::GlStubCalled("glBeginQuery");
  }

  void APIENTRY glBeginTransformFeedback(GLenum primitiveMode) {
    mithril::GlStubCalled("glBeginTransformFeedback");
  }

  void APIENTRY glBindAttribLocation(GLuint program, GLuint index, const GLchar *name) {
    mithril::GlStubCalled("glBindAttribLocation");
  }

  void APIENTRY glBindBuffer(GLenum target, GLuint buffer) {
    mithril::GlStubCalled("glBindBuffer");
  }

  void APIENTRY glBindBufferBase(GLenum target, GLuint index, GLuint buffer) {
    mithril::GlStubCalled("glBindBufferBase");
  }

  void APIENTRY glBindBufferRange(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size) {
    mithril::GlStubCalled("glBindBufferRange");
  }

  void APIENTRY glBindFragDataLocation(GLuint program, GLuint color, const GLchar *name) {
    mithril::GlStubCalled("glBindFragDataLocation");
  }

  void APIENTRY glBindFragDataLocationIndexed(GLuint program, GLuint colorNumber, GLuint index, const GLchar *name) {
    mithril::GlStubCalled("glBindFragDataLocationIndexed");
  }

  void APIENTRY glBindFramebuffer(GLenum target, GLuint framebuffer) {
    mithril::GlStubCalled("glBindFramebuffer");
  }

  void APIENTRY glBindRenderbuffer(GLenum target, GLuint renderbuffer) {
    mithril::GlStubCalled("glBindRenderbuffer");
  }

  void APIENTRY glBindSampler(GLuint unit, GLuint sampler) {
    mithril::GlStubCalled("glBindSampler");
  }

  void APIENTRY glBindTexture(GLenum target, GLuint texture) {
    mithril::GlStubCalled("glBindTexture");
  }

  void APIENTRY glBindVertexArray(GLuint array) {
    mithril::GlStubCalled("glBindVertexArray");
  }

  void APIENTRY glBlitFramebuffer(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter) {
    mithril::GlStubCalled("glBlitFramebuffer");
  }

  void APIENTRY glBufferData(GLenum target, GLsizeiptr size, const void *data, GLenum usage) {
    mithril::GlStubCalled("glBufferData");
  }

  void APIENTRY glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const void *data) {
    mithril::GlStubCalled("glBufferSubData");
  }

  GLenum APIENTRY glCheckFramebufferStatus(GLenum target) {
    mithril::GlStubCalled("glCheckFramebufferStatus");
    return 0;
  }

  void APIENTRY glClearBufferfi(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil) {
    mithril::GlStubCalled("glClearBufferfi");
  }

  void APIENTRY glClearBufferfv(GLenum buffer, GLint drawbuffer, const GLfloat *value) {
    mithril::GlStubCalled("glClearBufferfv");
  }

  void APIENTRY glClearBufferiv(GLenum buffer, GLint drawbuffer, const GLint *value) {
    mithril::GlStubCalled("glClearBufferiv");
  }

  void APIENTRY glClearBufferuiv(GLenum buffer, GLint drawbuffer, const GLuint *value) {
    mithril::GlStubCalled("glClearBufferuiv");
  }

  GLenum APIENTRY glClientWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout) {
    mithril::GlStubCalled("glClientWaitSync");
    return 0;
  }

  void APIENTRY glCompileShader(GLuint shader) {
    mithril::GlStubCalled("glCompileShader");
  }

  void APIENTRY glCompressedTexImage1D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const void *data) {
    mithril::GlStubCalled("glCompressedTexImage1D");
  }

  void APIENTRY glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data) {
    mithril::GlStubCalled("glCompressedTexImage2D");
  }

  void APIENTRY glCompressedTexImage3D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data) {
    mithril::GlStubCalled("glCompressedTexImage3D");
  }

  void APIENTRY glCompressedTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void *data) {
    mithril::GlStubCalled("glCompressedTexSubImage1D");
  }

  void APIENTRY glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data) {
    mithril::GlStubCalled("glCompressedTexSubImage2D");
  }

  void APIENTRY glCompressedTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data) {
    mithril::GlStubCalled("glCompressedTexSubImage3D");
  }

  void APIENTRY glCopyBufferSubData(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size) {
    mithril::GlStubCalled("glCopyBufferSubData");
  }

  void APIENTRY glCopyTexImage1D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border) {
    mithril::GlStubCalled("glCopyTexImage1D");
  }

  void APIENTRY glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border) {
    mithril::GlStubCalled("glCopyTexImage2D");
  }

  void APIENTRY glCopyTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width) {
    mithril::GlStubCalled("glCopyTexSubImage1D");
  }

  void APIENTRY glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height) {
    mithril::GlStubCalled("glCopyTexSubImage2D");
  }

  void APIENTRY glCopyTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height) {
    mithril::GlStubCalled("glCopyTexSubImage3D");
  }

  GLuint APIENTRY glCreateProgram(void) {
    mithril::GlStubCalled("glCreateProgram");
    return 0;
  }

  GLuint APIENTRY glCreateShader(GLenum type) {
    mithril::GlStubCalled("glCreateShader");
    return 0;
  }

  void APIENTRY glDeleteBuffers(GLsizei n, const GLuint *buffers) {
    mithril::GlStubCalled("glDeleteBuffers");
  }

  void APIENTRY glDeleteFramebuffers(GLsizei n, const GLuint *framebuffers) {
    mithril::GlStubCalled("glDeleteFramebuffers");
  }

  void APIENTRY glDeleteProgram(GLuint program) {
    mithril::GlStubCalled("glDeleteProgram");
  }

  void APIENTRY glDeleteQueries(GLsizei n, const GLuint *ids) {
    mithril::GlStubCalled("glDeleteQueries");
  }

  void APIENTRY glDeleteRenderbuffers(GLsizei n, const GLuint *renderbuffers) {
    mithril::GlStubCalled("glDeleteRenderbuffers");
  }

  void APIENTRY glDeleteSamplers(GLsizei count, const GLuint *samplers) {
    mithril::GlStubCalled("glDeleteSamplers");
  }

  void APIENTRY glDeleteShader(GLuint shader) {
    mithril::GlStubCalled("glDeleteShader");
  }

  void APIENTRY glDeleteSync(GLsync sync) {
    mithril::GlStubCalled("glDeleteSync");
  }

  void APIENTRY glDeleteTextures(GLsizei n, const GLuint *textures) {
    mithril::GlStubCalled("glDeleteTextures");
  }

  void APIENTRY glDeleteVertexArrays(GLsizei n, const GLuint *arrays) {
    mithril::GlStubCalled("glDeleteVertexArrays");
  }

  void APIENTRY glDetachShader(GLuint program, GLuint shader) {
    mithril::GlStubCalled("glDetachShader");
  }

  void APIENTRY glDisableVertexAttribArray(GLuint index) {
    mithril::GlStubCalled("glDisableVertexAttribArray");
  }

  void APIENTRY glDrawArrays(GLenum mode, GLint first, GLsizei count) {
    mithril::GlStubCalled("glDrawArrays");
  }

  void APIENTRY glDrawArraysInstanced(GLenum mode, GLint first, GLsizei count, GLsizei instancecount) {
    mithril::GlStubCalled("glDrawArraysInstanced");
  }

  void APIENTRY glDrawBuffer(GLenum buf) {
    mithril::GlStubCalled("glDrawBuffer");
  }

  void APIENTRY glDrawBuffers(GLsizei n, const GLenum *bufs) {
    mithril::GlStubCalled("glDrawBuffers");
  }

  void APIENTRY glDrawElements(GLenum mode, GLsizei count, GLenum type, const void *indices) {
    mithril::GlStubCalled("glDrawElements");
  }

  void APIENTRY glDrawElementsBaseVertex(GLenum mode, GLsizei count, GLenum type, const void *indices, GLint basevertex) {
    mithril::GlStubCalled("glDrawElementsBaseVertex");
  }

  void APIENTRY glDrawElementsInstanced(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount) {
    mithril::GlStubCalled("glDrawElementsInstanced");
  }

  void APIENTRY glDrawElementsInstancedBaseVertex(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex) {
    mithril::GlStubCalled("glDrawElementsInstancedBaseVertex");
  }

  void APIENTRY glDrawRangeElements(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices) {
    mithril::GlStubCalled("glDrawRangeElements");
  }

  void APIENTRY glDrawRangeElementsBaseVertex(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices, GLint basevertex) {
    mithril::GlStubCalled("glDrawRangeElementsBaseVertex");
  }

  void APIENTRY glEnableVertexAttribArray(GLuint index) {
    mithril::GlStubCalled("glEnableVertexAttribArray");
  }

  void APIENTRY glEndConditionalRender(void) {
    mithril::GlStubCalled("glEndConditionalRender");
  }

  void APIENTRY glEndQuery(GLenum target) {
    mithril::GlStubCalled("glEndQuery");
  }

  void APIENTRY glEndTransformFeedback(void) {
    mithril::GlStubCalled("glEndTransformFeedback");
  }

  GLsync APIENTRY glFenceSync(GLenum condition, GLbitfield flags) {
    mithril::GlStubCalled("glFenceSync");
    return nullptr;
  }

  void APIENTRY glFlushMappedBufferRange(GLenum target, GLintptr offset, GLsizeiptr length) {
    mithril::GlStubCalled("glFlushMappedBufferRange");
  }

  void APIENTRY glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer) {
    mithril::GlStubCalled("glFramebufferRenderbuffer");
  }

  void APIENTRY glFramebufferTexture(GLenum target, GLenum attachment, GLuint texture, GLint level) {
    mithril::GlStubCalled("glFramebufferTexture");
  }

  void APIENTRY glFramebufferTexture1D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) {
    mithril::GlStubCalled("glFramebufferTexture1D");
  }

  void APIENTRY glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) {
    mithril::GlStubCalled("glFramebufferTexture2D");
  }

  void APIENTRY glFramebufferTexture3D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset) {
    mithril::GlStubCalled("glFramebufferTexture3D");
  }

  void APIENTRY glFramebufferTextureLayer(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer) {
    mithril::GlStubCalled("glFramebufferTextureLayer");
  }

  void APIENTRY glGenBuffers(GLsizei n, GLuint *buffers) {
    mithril::GlStubCalled("glGenBuffers");
  }

  void APIENTRY glGenFramebuffers(GLsizei n, GLuint *framebuffers) {
    mithril::GlStubCalled("glGenFramebuffers");
  }

  void APIENTRY glGenQueries(GLsizei n, GLuint *ids) {
    mithril::GlStubCalled("glGenQueries");
  }

  void APIENTRY glGenRenderbuffers(GLsizei n, GLuint *renderbuffers) {
    mithril::GlStubCalled("glGenRenderbuffers");
  }

  void APIENTRY glGenSamplers(GLsizei count, GLuint *samplers) {
    mithril::GlStubCalled("glGenSamplers");
  }

  void APIENTRY glGenTextures(GLsizei n, GLuint *textures) {
    mithril::GlStubCalled("glGenTextures");
  }

  void APIENTRY glGenVertexArrays(GLsizei n, GLuint *arrays) {
    mithril::GlStubCalled("glGenVertexArrays");
  }

  void APIENTRY glGenerateMipmap(GLenum target) {
    mithril::GlStubCalled("glGenerateMipmap");
  }

  void APIENTRY glGetActiveAttrib(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name) {
    mithril::GlStubCalled("glGetActiveAttrib");
  }

  void APIENTRY glGetActiveUniform(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name) {
    mithril::GlStubCalled("glGetActiveUniform");
  }

  void APIENTRY glGetActiveUniformBlockName(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName) {
    mithril::GlStubCalled("glGetActiveUniformBlockName");
  }

  void APIENTRY glGetActiveUniformBlockiv(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetActiveUniformBlockiv");
  }

  void APIENTRY glGetActiveUniformName(GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformName) {
    mithril::GlStubCalled("glGetActiveUniformName");
  }

  void APIENTRY glGetActiveUniformsiv(GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetActiveUniformsiv");
  }

  void APIENTRY glGetAttachedShaders(GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders) {
    mithril::GlStubCalled("glGetAttachedShaders");
  }

  GLint APIENTRY glGetAttribLocation(GLuint program, const GLchar *name) {
    mithril::GlStubCalled("glGetAttribLocation");
    return 0;
  }

  void APIENTRY glGetBufferParameteri64v(GLenum target, GLenum pname, GLint64 *params) {
    mithril::GlStubCalled("glGetBufferParameteri64v");
  }

  void APIENTRY glGetBufferParameteriv(GLenum target, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetBufferParameteriv");
  }

  void APIENTRY glGetBufferPointerv(GLenum target, GLenum pname, void **params) {
    mithril::GlStubCalled("glGetBufferPointerv");
  }

  void APIENTRY glGetBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, void *data) {
    mithril::GlStubCalled("glGetBufferSubData");
  }

  void APIENTRY glGetCompressedTexImage(GLenum target, GLint level, void *img) {
    mithril::GlStubCalled("glGetCompressedTexImage");
  }

  GLint APIENTRY glGetFragDataIndex(GLuint program, const GLchar *name) {
    mithril::GlStubCalled("glGetFragDataIndex");
    return 0;
  }

  GLint APIENTRY glGetFragDataLocation(GLuint program, const GLchar *name) {
    mithril::GlStubCalled("glGetFragDataLocation");
    return 0;
  }

  void APIENTRY glGetFramebufferAttachmentParameteriv(GLenum target, GLenum attachment, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetFramebufferAttachmentParameteriv");
  }

  void APIENTRY glGetMultisamplefv(GLenum pname, GLuint index, GLfloat *val) {
    mithril::GlStubCalled("glGetMultisamplefv");
  }

  void APIENTRY glGetProgramInfoLog(GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog) {
    mithril::GlStubCalled("glGetProgramInfoLog");
  }

  void APIENTRY glGetProgramiv(GLuint program, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetProgramiv");
  }

  void APIENTRY glGetQueryObjecti64v(GLuint id, GLenum pname, GLint64 *params) {
    mithril::GlStubCalled("glGetQueryObjecti64v");
  }

  void APIENTRY glGetQueryObjectiv(GLuint id, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetQueryObjectiv");
  }

  void APIENTRY glGetQueryObjectui64v(GLuint id, GLenum pname, GLuint64 *params) {
    mithril::GlStubCalled("glGetQueryObjectui64v");
  }

  void APIENTRY glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint *params) {
    mithril::GlStubCalled("glGetQueryObjectuiv");
  }

  void APIENTRY glGetQueryiv(GLenum target, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetQueryiv");
  }

  void APIENTRY glGetRenderbufferParameteriv(GLenum target, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetRenderbufferParameteriv");
  }

  void APIENTRY glGetSamplerParameterIiv(GLuint sampler, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetSamplerParameterIiv");
  }

  void APIENTRY glGetSamplerParameterIuiv(GLuint sampler, GLenum pname, GLuint *params) {
    mithril::GlStubCalled("glGetSamplerParameterIuiv");
  }

  void APIENTRY glGetSamplerParameterfv(GLuint sampler, GLenum pname, GLfloat *params) {
    mithril::GlStubCalled("glGetSamplerParameterfv");
  }

  void APIENTRY glGetSamplerParameteriv(GLuint sampler, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetSamplerParameteriv");
  }

  void APIENTRY glGetShaderInfoLog(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog) {
    mithril::GlStubCalled("glGetShaderInfoLog");
  }

  void APIENTRY glGetShaderSource(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source) {
    mithril::GlStubCalled("glGetShaderSource");
  }

  void APIENTRY glGetShaderiv(GLuint shader, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetShaderiv");
  }

  void APIENTRY glGetSynciv(GLsync sync, GLenum pname, GLsizei count, GLsizei *length, GLint *values) {
    mithril::GlStubCalled("glGetSynciv");
  }

  void APIENTRY glGetTexImage(GLenum target, GLint level, GLenum format, GLenum type, void *pixels) {
    mithril::GlStubCalled("glGetTexImage");
  }

  void APIENTRY glGetTexLevelParameterfv(GLenum target, GLint level, GLenum pname, GLfloat *params) {
    mithril::GlStubCalled("glGetTexLevelParameterfv");
  }

  void APIENTRY glGetTexLevelParameteriv(GLenum target, GLint level, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetTexLevelParameteriv");
  }

  void APIENTRY glGetTexParameterIiv(GLenum target, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetTexParameterIiv");
  }

  void APIENTRY glGetTexParameterIuiv(GLenum target, GLenum pname, GLuint *params) {
    mithril::GlStubCalled("glGetTexParameterIuiv");
  }

  void APIENTRY glGetTexParameterfv(GLenum target, GLenum pname, GLfloat *params) {
    mithril::GlStubCalled("glGetTexParameterfv");
  }

  void APIENTRY glGetTexParameteriv(GLenum target, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetTexParameteriv");
  }

  void APIENTRY glGetTransformFeedbackVarying(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name) {
    mithril::GlStubCalled("glGetTransformFeedbackVarying");
  }

  GLuint APIENTRY glGetUniformBlockIndex(GLuint program, const GLchar *uniformBlockName) {
    mithril::GlStubCalled("glGetUniformBlockIndex");
    return 0;
  }

  void APIENTRY glGetUniformIndices(GLuint program, GLsizei uniformCount, const GLchar *const*uniformNames, GLuint *uniformIndices) {
    mithril::GlStubCalled("glGetUniformIndices");
  }

  GLint APIENTRY glGetUniformLocation(GLuint program, const GLchar *name) {
    mithril::GlStubCalled("glGetUniformLocation");
    return 0;
  }

  void APIENTRY glGetUniformfv(GLuint program, GLint location, GLfloat *params) {
    mithril::GlStubCalled("glGetUniformfv");
  }

  void APIENTRY glGetUniformiv(GLuint program, GLint location, GLint *params) {
    mithril::GlStubCalled("glGetUniformiv");
  }

  void APIENTRY glGetUniformuiv(GLuint program, GLint location, GLuint *params) {
    mithril::GlStubCalled("glGetUniformuiv");
  }

  void APIENTRY glGetVertexAttribIiv(GLuint index, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetVertexAttribIiv");
  }

  void APIENTRY glGetVertexAttribIuiv(GLuint index, GLenum pname, GLuint *params) {
    mithril::GlStubCalled("glGetVertexAttribIuiv");
  }

  void APIENTRY glGetVertexAttribPointerv(GLuint index, GLenum pname, void **pointer) {
    mithril::GlStubCalled("glGetVertexAttribPointerv");
  }

  void APIENTRY glGetVertexAttribdv(GLuint index, GLenum pname, GLdouble *params) {
    mithril::GlStubCalled("glGetVertexAttribdv");
  }

  void APIENTRY glGetVertexAttribfv(GLuint index, GLenum pname, GLfloat *params) {
    mithril::GlStubCalled("glGetVertexAttribfv");
  }

  void APIENTRY glGetVertexAttribiv(GLuint index, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetVertexAttribiv");
  }

  GLboolean APIENTRY glIsBuffer(GLuint buffer) {
    mithril::GlStubCalled("glIsBuffer");
    return 0;
  }

  GLboolean APIENTRY glIsFramebuffer(GLuint framebuffer) {
    mithril::GlStubCalled("glIsFramebuffer");
    return 0;
  }

  GLboolean APIENTRY glIsProgram(GLuint program) {
    mithril::GlStubCalled("glIsProgram");
    return 0;
  }

  GLboolean APIENTRY glIsQuery(GLuint id) {
    mithril::GlStubCalled("glIsQuery");
    return 0;
  }

  GLboolean APIENTRY glIsRenderbuffer(GLuint renderbuffer) {
    mithril::GlStubCalled("glIsRenderbuffer");
    return 0;
  }

  GLboolean APIENTRY glIsSampler(GLuint sampler) {
    mithril::GlStubCalled("glIsSampler");
    return 0;
  }

  GLboolean APIENTRY glIsShader(GLuint shader) {
    mithril::GlStubCalled("glIsShader");
    return 0;
  }

  GLboolean APIENTRY glIsSync(GLsync sync) {
    mithril::GlStubCalled("glIsSync");
    return 0;
  }

  GLboolean APIENTRY glIsTexture(GLuint texture) {
    mithril::GlStubCalled("glIsTexture");
    return 0;
  }

  GLboolean APIENTRY glIsVertexArray(GLuint array) {
    mithril::GlStubCalled("glIsVertexArray");
    return 0;
  }

  void APIENTRY glLinkProgram(GLuint program) {
    mithril::GlStubCalled("glLinkProgram");
  }

  void * APIENTRY glMapBuffer(GLenum target, GLenum access) {
    mithril::GlStubCalled("glMapBuffer");
    return nullptr;
  }

  void * APIENTRY glMapBufferRange(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access) {
    mithril::GlStubCalled("glMapBufferRange");
    return nullptr;
  }

  void APIENTRY glMultiDrawArrays(GLenum mode, const GLint *first, const GLsizei *count, GLsizei drawcount) {
    mithril::GlStubCalled("glMultiDrawArrays");
  }

  void APIENTRY glMultiDrawElements(GLenum mode, const GLsizei *count, GLenum type, const void *const*indices, GLsizei drawcount) {
    mithril::GlStubCalled("glMultiDrawElements");
  }

  void APIENTRY glMultiDrawElementsBaseVertex(GLenum mode, const GLsizei *count, GLenum type, const void *const*indices, GLsizei drawcount, const GLint *basevertex) {
    mithril::GlStubCalled("glMultiDrawElementsBaseVertex");
  }

  void APIENTRY glPixelStoref(GLenum pname, GLfloat param) {
    mithril::GlStubCalled("glPixelStoref");
  }

  void APIENTRY glPointParameterf(GLenum pname, GLfloat param) {
    mithril::GlStubCalled("glPointParameterf");
  }

  void APIENTRY glPointParameterfv(GLenum pname, const GLfloat *params) {
    mithril::GlStubCalled("glPointParameterfv");
  }

  void APIENTRY glPointParameteri(GLenum pname, GLint param) {
    mithril::GlStubCalled("glPointParameteri");
  }

  void APIENTRY glPointParameteriv(GLenum pname, const GLint *params) {
    mithril::GlStubCalled("glPointParameteriv");
  }

  void APIENTRY glPrimitiveRestartIndex(GLuint index) {
    mithril::GlStubCalled("glPrimitiveRestartIndex");
  }

  void APIENTRY glProvokingVertex(GLenum mode) {
    mithril::GlStubCalled("glProvokingVertex");
  }

  void APIENTRY glQueryCounter(GLuint id, GLenum target) {
    mithril::GlStubCalled("glQueryCounter");
  }

  void APIENTRY glReadBuffer(GLenum src) {
    mithril::GlStubCalled("glReadBuffer");
  }

  void APIENTRY glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels) {
    mithril::GlStubCalled("glReadPixels");
  }

  void APIENTRY glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height) {
    mithril::GlStubCalled("glRenderbufferStorage");
  }

  void APIENTRY glRenderbufferStorageMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height) {
    mithril::GlStubCalled("glRenderbufferStorageMultisample");
  }

  void APIENTRY glSamplerParameterIiv(GLuint sampler, GLenum pname, const GLint *param) {
    mithril::GlStubCalled("glSamplerParameterIiv");
  }

  void APIENTRY glSamplerParameterIuiv(GLuint sampler, GLenum pname, const GLuint *param) {
    mithril::GlStubCalled("glSamplerParameterIuiv");
  }

  void APIENTRY glSamplerParameterf(GLuint sampler, GLenum pname, GLfloat param) {
    mithril::GlStubCalled("glSamplerParameterf");
  }

  void APIENTRY glSamplerParameterfv(GLuint sampler, GLenum pname, const GLfloat *param) {
    mithril::GlStubCalled("glSamplerParameterfv");
  }

  void APIENTRY glSamplerParameteri(GLuint sampler, GLenum pname, GLint param) {
    mithril::GlStubCalled("glSamplerParameteri");
  }

  void APIENTRY glSamplerParameteriv(GLuint sampler, GLenum pname, const GLint *param) {
    mithril::GlStubCalled("glSamplerParameteriv");
  }

  void APIENTRY glShaderSource(GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length) {
    mithril::GlStubCalled("glShaderSource");
  }

  void APIENTRY glTexBuffer(GLenum target, GLenum internalformat, GLuint buffer) {
    mithril::GlStubCalled("glTexBuffer");
  }

  void APIENTRY glTexImage1D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const void *pixels) {
    mithril::GlStubCalled("glTexImage1D");
  }

  void APIENTRY glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels) {
    mithril::GlStubCalled("glTexImage2D");
  }

  void APIENTRY glTexImage2DMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations) {
    mithril::GlStubCalled("glTexImage2DMultisample");
  }

  void APIENTRY glTexImage3D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels) {
    mithril::GlStubCalled("glTexImage3D");
  }

  void APIENTRY glTexImage3DMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations) {
    mithril::GlStubCalled("glTexImage3DMultisample");
  }

  void APIENTRY glTexParameterIiv(GLenum target, GLenum pname, const GLint *params) {
    mithril::GlStubCalled("glTexParameterIiv");
  }

  void APIENTRY glTexParameterIuiv(GLenum target, GLenum pname, const GLuint *params) {
    mithril::GlStubCalled("glTexParameterIuiv");
  }

  void APIENTRY glTexParameterf(GLenum target, GLenum pname, GLfloat param) {
    mithril::GlStubCalled("glTexParameterf");
  }

  void APIENTRY glTexParameterfv(GLenum target, GLenum pname, const GLfloat *params) {
    mithril::GlStubCalled("glTexParameterfv");
  }

  void APIENTRY glTexParameteri(GLenum target, GLenum pname, GLint param) {
    mithril::GlStubCalled("glTexParameteri");
  }

  void APIENTRY glTexParameteriv(GLenum target, GLenum pname, const GLint *params) {
    mithril::GlStubCalled("glTexParameteriv");
  }

  void APIENTRY glTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void *pixels) {
    mithril::GlStubCalled("glTexSubImage1D");
  }

  void APIENTRY glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels) {
    mithril::GlStubCalled("glTexSubImage2D");
  }

  void APIENTRY glTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels) {
    mithril::GlStubCalled("glTexSubImage3D");
  }

  void APIENTRY glTransformFeedbackVaryings(GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode) {
    mithril::GlStubCalled("glTransformFeedbackVaryings");
  }

  void APIENTRY glUniform1f(GLint location, GLfloat v0) {
    mithril::GlStubCalled("glUniform1f");
  }

  void APIENTRY glUniform1fv(GLint location, GLsizei count, const GLfloat *value) {
    mithril::GlStubCalled("glUniform1fv");
  }

  void APIENTRY glUniform1i(GLint location, GLint v0) {
    mithril::GlStubCalled("glUniform1i");
  }

  void APIENTRY glUniform1iv(GLint location, GLsizei count, const GLint *value) {
    mithril::GlStubCalled("glUniform1iv");
  }

  void APIENTRY glUniform1ui(GLint location, GLuint v0) {
    mithril::GlStubCalled("glUniform1ui");
  }

  void APIENTRY glUniform1uiv(GLint location, GLsizei count, const GLuint *value) {
    mithril::GlStubCalled("glUniform1uiv");
  }

  void APIENTRY glUniform2f(GLint location, GLfloat v0, GLfloat v1) {
    mithril::GlStubCalled("glUniform2f");
  }

  void APIENTRY glUniform2fv(GLint location, GLsizei count, const GLfloat *value) {
    mithril::GlStubCalled("glUniform2fv");
  }

  void APIENTRY glUniform2i(GLint location, GLint v0, GLint v1) {
    mithril::GlStubCalled("glUniform2i");
  }

  void APIENTRY glUniform2iv(GLint location, GLsizei count, const GLint *value) {
    mithril::GlStubCalled("glUniform2iv");
  }

  void APIENTRY glUniform2ui(GLint location, GLuint v0, GLuint v1) {
    mithril::GlStubCalled("glUniform2ui");
  }

  void APIENTRY glUniform2uiv(GLint location, GLsizei count, const GLuint *value) {
    mithril::GlStubCalled("glUniform2uiv");
  }

  void APIENTRY glUniform3f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2) {
    mithril::GlStubCalled("glUniform3f");
  }

  void APIENTRY glUniform3fv(GLint location, GLsizei count, const GLfloat *value) {
    mithril::GlStubCalled("glUniform3fv");
  }

  void APIENTRY glUniform3i(GLint location, GLint v0, GLint v1, GLint v2) {
    mithril::GlStubCalled("glUniform3i");
  }

  void APIENTRY glUniform3iv(GLint location, GLsizei count, const GLint *value) {
    mithril::GlStubCalled("glUniform3iv");
  }

  void APIENTRY glUniform3ui(GLint location, GLuint v0, GLuint v1, GLuint v2) {
    mithril::GlStubCalled("glUniform3ui");
  }

  void APIENTRY glUniform3uiv(GLint location, GLsizei count, const GLuint *value) {
    mithril::GlStubCalled("glUniform3uiv");
  }

  void APIENTRY glUniform4f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) {
    mithril::GlStubCalled("glUniform4f");
  }

  void APIENTRY glUniform4fv(GLint location, GLsizei count, const GLfloat *value) {
    mithril::GlStubCalled("glUniform4fv");
  }

  void APIENTRY glUniform4i(GLint location, GLint v0, GLint v1, GLint v2, GLint v3) {
    mithril::GlStubCalled("glUniform4i");
  }

  void APIENTRY glUniform4iv(GLint location, GLsizei count, const GLint *value) {
    mithril::GlStubCalled("glUniform4iv");
  }

  void APIENTRY glUniform4ui(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3) {
    mithril::GlStubCalled("glUniform4ui");
  }

  void APIENTRY glUniform4uiv(GLint location, GLsizei count, const GLuint *value) {
    mithril::GlStubCalled("glUniform4uiv");
  }

  void APIENTRY glUniformBlockBinding(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding) {
    mithril::GlStubCalled("glUniformBlockBinding");
  }

  void APIENTRY glUniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    mithril::GlStubCalled("glUniformMatrix2fv");
  }

  void APIENTRY glUniformMatrix2x3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    mithril::GlStubCalled("glUniformMatrix2x3fv");
  }

  void APIENTRY glUniformMatrix2x4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    mithril::GlStubCalled("glUniformMatrix2x4fv");
  }

  void APIENTRY glUniformMatrix3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    mithril::GlStubCalled("glUniformMatrix3fv");
  }

  void APIENTRY glUniformMatrix3x2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    mithril::GlStubCalled("glUniformMatrix3x2fv");
  }

  void APIENTRY glUniformMatrix3x4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    mithril::GlStubCalled("glUniformMatrix3x4fv");
  }

  void APIENTRY glUniformMatrix4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    mithril::GlStubCalled("glUniformMatrix4fv");
  }

  void APIENTRY glUniformMatrix4x2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    mithril::GlStubCalled("glUniformMatrix4x2fv");
  }

  void APIENTRY glUniformMatrix4x3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    mithril::GlStubCalled("glUniformMatrix4x3fv");
  }

  GLboolean APIENTRY glUnmapBuffer(GLenum target) {
    mithril::GlStubCalled("glUnmapBuffer");
    return 0;
  }

  void APIENTRY glUseProgram(GLuint program) {
    mithril::GlStubCalled("glUseProgram");
  }

  void APIENTRY glValidateProgram(GLuint program) {
    mithril::GlStubCalled("glValidateProgram");
  }

  void APIENTRY glVertexAttrib1d(GLuint index, GLdouble x) {
    mithril::GlStubCalled("glVertexAttrib1d");
  }

  void APIENTRY glVertexAttrib1dv(GLuint index, const GLdouble *v) {
    mithril::GlStubCalled("glVertexAttrib1dv");
  }

  void APIENTRY glVertexAttrib1f(GLuint index, GLfloat x) {
    mithril::GlStubCalled("glVertexAttrib1f");
  }

  void APIENTRY glVertexAttrib1fv(GLuint index, const GLfloat *v) {
    mithril::GlStubCalled("glVertexAttrib1fv");
  }

  void APIENTRY glVertexAttrib1s(GLuint index, GLshort x) {
    mithril::GlStubCalled("glVertexAttrib1s");
  }

  void APIENTRY glVertexAttrib1sv(GLuint index, const GLshort *v) {
    mithril::GlStubCalled("glVertexAttrib1sv");
  }

  void APIENTRY glVertexAttrib2d(GLuint index, GLdouble x, GLdouble y) {
    mithril::GlStubCalled("glVertexAttrib2d");
  }

  void APIENTRY glVertexAttrib2dv(GLuint index, const GLdouble *v) {
    mithril::GlStubCalled("glVertexAttrib2dv");
  }

  void APIENTRY glVertexAttrib2f(GLuint index, GLfloat x, GLfloat y) {
    mithril::GlStubCalled("glVertexAttrib2f");
  }

  void APIENTRY glVertexAttrib2fv(GLuint index, const GLfloat *v) {
    mithril::GlStubCalled("glVertexAttrib2fv");
  }

  void APIENTRY glVertexAttrib2s(GLuint index, GLshort x, GLshort y) {
    mithril::GlStubCalled("glVertexAttrib2s");
  }

  void APIENTRY glVertexAttrib2sv(GLuint index, const GLshort *v) {
    mithril::GlStubCalled("glVertexAttrib2sv");
  }

  void APIENTRY glVertexAttrib3d(GLuint index, GLdouble x, GLdouble y, GLdouble z) {
    mithril::GlStubCalled("glVertexAttrib3d");
  }

  void APIENTRY glVertexAttrib3dv(GLuint index, const GLdouble *v) {
    mithril::GlStubCalled("glVertexAttrib3dv");
  }

  void APIENTRY glVertexAttrib3f(GLuint index, GLfloat x, GLfloat y, GLfloat z) {
    mithril::GlStubCalled("glVertexAttrib3f");
  }

  void APIENTRY glVertexAttrib3fv(GLuint index, const GLfloat *v) {
    mithril::GlStubCalled("glVertexAttrib3fv");
  }

  void APIENTRY glVertexAttrib3s(GLuint index, GLshort x, GLshort y, GLshort z) {
    mithril::GlStubCalled("glVertexAttrib3s");
  }

  void APIENTRY glVertexAttrib3sv(GLuint index, const GLshort *v) {
    mithril::GlStubCalled("glVertexAttrib3sv");
  }

  void APIENTRY glVertexAttrib4Nbv(GLuint index, const GLbyte *v) {
    mithril::GlStubCalled("glVertexAttrib4Nbv");
  }

  void APIENTRY glVertexAttrib4Niv(GLuint index, const GLint *v) {
    mithril::GlStubCalled("glVertexAttrib4Niv");
  }

  void APIENTRY glVertexAttrib4Nsv(GLuint index, const GLshort *v) {
    mithril::GlStubCalled("glVertexAttrib4Nsv");
  }

  void APIENTRY glVertexAttrib4Nub(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w) {
    mithril::GlStubCalled("glVertexAttrib4Nub");
  }

  void APIENTRY glVertexAttrib4Nubv(GLuint index, const GLubyte *v) {
    mithril::GlStubCalled("glVertexAttrib4Nubv");
  }

  void APIENTRY glVertexAttrib4Nuiv(GLuint index, const GLuint *v) {
    mithril::GlStubCalled("glVertexAttrib4Nuiv");
  }

  void APIENTRY glVertexAttrib4Nusv(GLuint index, const GLushort *v) {
    mithril::GlStubCalled("glVertexAttrib4Nusv");
  }

  void APIENTRY glVertexAttrib4bv(GLuint index, const GLbyte *v) {
    mithril::GlStubCalled("glVertexAttrib4bv");
  }

  void APIENTRY glVertexAttrib4d(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w) {
    mithril::GlStubCalled("glVertexAttrib4d");
  }

  void APIENTRY glVertexAttrib4dv(GLuint index, const GLdouble *v) {
    mithril::GlStubCalled("glVertexAttrib4dv");
  }

  void APIENTRY glVertexAttrib4f(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w) {
    mithril::GlStubCalled("glVertexAttrib4f");
  }

  void APIENTRY glVertexAttrib4fv(GLuint index, const GLfloat *v) {
    mithril::GlStubCalled("glVertexAttrib4fv");
  }

  void APIENTRY glVertexAttrib4iv(GLuint index, const GLint *v) {
    mithril::GlStubCalled("glVertexAttrib4iv");
  }

  void APIENTRY glVertexAttrib4s(GLuint index, GLshort x, GLshort y, GLshort z, GLshort w) {
    mithril::GlStubCalled("glVertexAttrib4s");
  }

  void APIENTRY glVertexAttrib4sv(GLuint index, const GLshort *v) {
    mithril::GlStubCalled("glVertexAttrib4sv");
  }

  void APIENTRY glVertexAttrib4ubv(GLuint index, const GLubyte *v) {
    mithril::GlStubCalled("glVertexAttrib4ubv");
  }

  void APIENTRY glVertexAttrib4uiv(GLuint index, const GLuint *v) {
    mithril::GlStubCalled("glVertexAttrib4uiv");
  }

  void APIENTRY glVertexAttrib4usv(GLuint index, const GLushort *v) {
    mithril::GlStubCalled("glVertexAttrib4usv");
  }

  void APIENTRY glVertexAttribDivisor(GLuint index, GLuint divisor) {
    mithril::GlStubCalled("glVertexAttribDivisor");
  }

  void APIENTRY glVertexAttribI1i(GLuint index, GLint x) {
    mithril::GlStubCalled("glVertexAttribI1i");
  }

  void APIENTRY glVertexAttribI1iv(GLuint index, const GLint *v) {
    mithril::GlStubCalled("glVertexAttribI1iv");
  }

  void APIENTRY glVertexAttribI1ui(GLuint index, GLuint x) {
    mithril::GlStubCalled("glVertexAttribI1ui");
  }

  void APIENTRY glVertexAttribI1uiv(GLuint index, const GLuint *v) {
    mithril::GlStubCalled("glVertexAttribI1uiv");
  }

  void APIENTRY glVertexAttribI2i(GLuint index, GLint x, GLint y) {
    mithril::GlStubCalled("glVertexAttribI2i");
  }

  void APIENTRY glVertexAttribI2iv(GLuint index, const GLint *v) {
    mithril::GlStubCalled("glVertexAttribI2iv");
  }

  void APIENTRY glVertexAttribI2ui(GLuint index, GLuint x, GLuint y) {
    mithril::GlStubCalled("glVertexAttribI2ui");
  }

  void APIENTRY glVertexAttribI2uiv(GLuint index, const GLuint *v) {
    mithril::GlStubCalled("glVertexAttribI2uiv");
  }

  void APIENTRY glVertexAttribI3i(GLuint index, GLint x, GLint y, GLint z) {
    mithril::GlStubCalled("glVertexAttribI3i");
  }

  void APIENTRY glVertexAttribI3iv(GLuint index, const GLint *v) {
    mithril::GlStubCalled("glVertexAttribI3iv");
  }

  void APIENTRY glVertexAttribI3ui(GLuint index, GLuint x, GLuint y, GLuint z) {
    mithril::GlStubCalled("glVertexAttribI3ui");
  }

  void APIENTRY glVertexAttribI3uiv(GLuint index, const GLuint *v) {
    mithril::GlStubCalled("glVertexAttribI3uiv");
  }

  void APIENTRY glVertexAttribI4bv(GLuint index, const GLbyte *v) {
    mithril::GlStubCalled("glVertexAttribI4bv");
  }

  void APIENTRY glVertexAttribI4i(GLuint index, GLint x, GLint y, GLint z, GLint w) {
    mithril::GlStubCalled("glVertexAttribI4i");
  }

  void APIENTRY glVertexAttribI4iv(GLuint index, const GLint *v) {
    mithril::GlStubCalled("glVertexAttribI4iv");
  }

  void APIENTRY glVertexAttribI4sv(GLuint index, const GLshort *v) {
    mithril::GlStubCalled("glVertexAttribI4sv");
  }

  void APIENTRY glVertexAttribI4ubv(GLuint index, const GLubyte *v) {
    mithril::GlStubCalled("glVertexAttribI4ubv");
  }

  void APIENTRY glVertexAttribI4ui(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w) {
    mithril::GlStubCalled("glVertexAttribI4ui");
  }

  void APIENTRY glVertexAttribI4uiv(GLuint index, const GLuint *v) {
    mithril::GlStubCalled("glVertexAttribI4uiv");
  }

  void APIENTRY glVertexAttribI4usv(GLuint index, const GLushort *v) {
    mithril::GlStubCalled("glVertexAttribI4usv");
  }

  void APIENTRY glVertexAttribIPointer(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer) {
    mithril::GlStubCalled("glVertexAttribIPointer");
  }

  void APIENTRY glVertexAttribP1ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP1ui");
  }

  void APIENTRY glVertexAttribP1uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP1uiv");
  }

  void APIENTRY glVertexAttribP2ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP2ui");
  }

  void APIENTRY glVertexAttribP2uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP2uiv");
  }

  void APIENTRY glVertexAttribP3ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP3ui");
  }

  void APIENTRY glVertexAttribP3uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP3uiv");
  }

  void APIENTRY glVertexAttribP4ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP4ui");
  }

  void APIENTRY glVertexAttribP4uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP4uiv");
  }

  void APIENTRY glVertexAttribPointer(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer) {
    mithril::GlStubCalled("glVertexAttribPointer");
  }

  void APIENTRY glWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout) {
    mithril::GlStubCalled("glWaitSync");
  }

} // extern "C"
