// Mithril-Wrapper GL entry points -- stub table.
// GENERATED by scripts/gen_gl_stubs.py -- DO NOT EDIT BY HAND.
#include <GL/glcorearb.h>

namespace mithril {
void GlStubCalled(const char* name);
} // namespace mithril

extern "C" {

  void APIENTRY glActiveTexture(GLenum texture) {
    mithril::GlStubCalled("glActiveTexture");
  }

  void APIENTRY glBeginConditionalRender(GLuint id, GLenum mode) {
    mithril::GlStubCalled("glBeginConditionalRender");
  }

  void APIENTRY glBeginQuery(GLenum target, GLuint id) {
    mithril::GlStubCalled("glBeginQuery");
  }

  void APIENTRY glBeginTransformFeedback(GLenum primitiveMode) {
    mithril::GlStubCalled("glBeginTransformFeedback");
  }

  void APIENTRY glBindBufferBase(GLenum target, GLuint index, GLuint buffer) {
    mithril::GlStubCalled("glBindBufferBase");
  }

  void APIENTRY glBindBufferRange(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size) {
    mithril::GlStubCalled("glBindBufferRange");
  }

  void APIENTRY glBindFragDataLocation(GLuint program, GLuint color, const GLchar *name) {
    mithril::GlStubCalled("glBindFragDataLocation");
  }

  void APIENTRY glBindFragDataLocationIndexed(GLuint program, GLuint colorNumber, GLuint index, const GLchar *name) {
    mithril::GlStubCalled("glBindFragDataLocationIndexed");
  }

  void APIENTRY glBindFramebuffer(GLenum target, GLuint framebuffer) {
    mithril::GlStubCalled("glBindFramebuffer");
  }

  void APIENTRY glBindRenderbuffer(GLenum target, GLuint renderbuffer) {
    mithril::GlStubCalled("glBindRenderbuffer");
  }

  void APIENTRY glBindSampler(GLuint unit, GLuint sampler) {
    mithril::GlStubCalled("glBindSampler");
  }

  void APIENTRY glBindTexture(GLenum target, GLuint texture) {
    mithril::GlStubCalled("glBindTexture");
  }

  void APIENTRY glBlitFramebuffer(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter) {
    mithril::GlStubCalled("glBlitFramebuffer");
  }

  GLenum APIENTRY glCheckFramebufferStatus(GLenum target) {
    mithril::GlStubCalled("glCheckFramebufferStatus");
    return 0;
  }

  void APIENTRY glClearBufferfi(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil) {
    mithril::GlStubCalled("glClearBufferfi");
  }

  void APIENTRY glClearBufferfv(GLenum buffer, GLint drawbuffer, const GLfloat *value) {
    mithril::GlStubCalled("glClearBufferfv");
  }

  void APIENTRY glClearBufferiv(GLenum buffer, GLint drawbuffer, const GLint *value) {
    mithril::GlStubCalled("glClearBufferiv");
  }

  void APIENTRY glClearBufferuiv(GLenum buffer, GLint drawbuffer, const GLuint *value) {
    mithril::GlStubCalled("glClearBufferuiv");
  }

  GLenum APIENTRY glClientWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout) {
    mithril::GlStubCalled("glClientWaitSync");
    return 0;
  }

  void APIENTRY glCompressedTexImage1D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const void *data) {
    mithril::GlStubCalled("glCompressedTexImage1D");
  }

  void APIENTRY glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data) {
    mithril::GlStubCalled("glCompressedTexImage2D");
  }

  void APIENTRY glCompressedTexImage3D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data) {
    mithril::GlStubCalled("glCompressedTexImage3D");
  }

  void APIENTRY glCompressedTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void *data) {
    mithril::GlStubCalled("glCompressedTexSubImage1D");
  }

  void APIENTRY glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data) {
    mithril::GlStubCalled("glCompressedTexSubImage2D");
  }

  void APIENTRY glCompressedTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data) {
    mithril::GlStubCalled("glCompressedTexSubImage3D");
  }

  void APIENTRY glCopyTexImage1D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border) {
    mithril::GlStubCalled("glCopyTexImage1D");
  }

  void APIENTRY glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border) {
    mithril::GlStubCalled("glCopyTexImage2D");
  }

  void APIENTRY glCopyTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width) {
    mithril::GlStubCalled("glCopyTexSubImage1D");
  }

  void APIENTRY glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height) {
    mithril::GlStubCalled("glCopyTexSubImage2D");
  }

  void APIENTRY glCopyTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height) {
    mithril::GlStubCalled("glCopyTexSubImage3D");
  }

  void APIENTRY glDeleteFramebuffers(GLsizei n, const GLuint *framebuffers) {
    mithril::GlStubCalled("glDeleteFramebuffers");
  }

  void APIENTRY glDeleteQueries(GLsizei n, const GLuint *ids) {
    mithril::GlStubCalled("glDeleteQueries");
  }

  void APIENTRY glDeleteRenderbuffers(GLsizei n, const GLuint *renderbuffers) {
    mithril::GlStubCalled("glDeleteRenderbuffers");
  }

  void APIENTRY glDeleteSamplers(GLsizei count, const GLuint *samplers) {
    mithril::GlStubCalled("glDeleteSamplers");
  }

  void APIENTRY glDeleteSync(GLsync sync) {
    mithril::GlStubCalled("glDeleteSync");
  }

  void APIENTRY glDeleteTextures(GLsizei n, const GLuint *textures) {
    mithril::GlStubCalled("glDeleteTextures");
  }

  void APIENTRY glDrawBuffer(GLenum buf) {
    mithril::GlStubCalled("glDrawBuffer");
  }

  void APIENTRY glDrawBuffers(GLsizei n, const GLenum *bufs) {
    mithril::GlStubCalled("glDrawBuffers");
  }

  void APIENTRY glEndConditionalRender(void) {
    mithril::GlStubCalled("glEndConditionalRender");
  }

  void APIENTRY glEndQuery(GLenum target) {
    mithril::GlStubCalled("glEndQuery");
  }

  void APIENTRY glEndTransformFeedback(void) {
    mithril::GlStubCalled("glEndTransformFeedback");
  }

  GLsync APIENTRY glFenceSync(GLenum condition, GLbitfield flags) {
    mithril::GlStubCalled("glFenceSync");
    return nullptr;
  }

  void APIENTRY glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer) {
    mithril::GlStubCalled("glFramebufferRenderbuffer");
  }

  void APIENTRY glFramebufferTexture(GLenum target, GLenum attachment, GLuint texture, GLint level) {
    mithril::GlStubCalled("glFramebufferTexture");
  }

  void APIENTRY glFramebufferTexture1D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) {
    mithril::GlStubCalled("glFramebufferTexture1D");
  }

  void APIENTRY glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) {
    mithril::GlStubCalled("glFramebufferTexture2D");
  }

  void APIENTRY glFramebufferTexture3D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset) {
    mithril::GlStubCalled("glFramebufferTexture3D");
  }

  void APIENTRY glFramebufferTextureLayer(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer) {
    mithril::GlStubCalled("glFramebufferTextureLayer");
  }

  void APIENTRY glGenFramebuffers(GLsizei n, GLuint *framebuffers) {
    mithril::GlStubCalled("glGenFramebuffers");
  }

  void APIENTRY glGenQueries(GLsizei n, GLuint *ids) {
    mithril::GlStubCalled("glGenQueries");
  }

  void APIENTRY glGenRenderbuffers(GLsizei n, GLuint *renderbuffers) {
    mithril::GlStubCalled("glGenRenderbuffers");
  }

  void APIENTRY glGenSamplers(GLsizei count, GLuint *samplers) {
    mithril::GlStubCalled("glGenSamplers");
  }

  void APIENTRY glGenTextures(GLsizei n, GLuint *textures) {
    mithril::GlStubCalled("glGenTextures");
  }

  void APIENTRY glGenerateMipmap(GLenum target) {
    mithril::GlStubCalled("glGenerateMipmap");
  }

  void APIENTRY glGetActiveUniformBlockName(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName) {
    mithril::GlStubCalled("glGetActiveUniformBlockName");
  }

  void APIENTRY glGetActiveUniformBlockiv(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetActiveUniformBlockiv");
  }

  void APIENTRY glGetActiveUniformName(GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformName) {
    mithril::GlStubCalled("glGetActiveUniformName");
  }

  void APIENTRY glGetActiveUniformsiv(GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetActiveUniformsiv");
  }

  void APIENTRY glGetCompressedTexImage(GLenum target, GLint level, void *img) {
    mithril::GlStubCalled("glGetCompressedTexImage");
  }

  GLint APIENTRY glGetFragDataIndex(GLuint program, const GLchar *name) {
    mithril::GlStubCalled("glGetFragDataIndex");
    return 0;
  }

  GLint APIENTRY glGetFragDataLocation(GLuint program, const GLchar *name) {
    mithril::GlStubCalled("glGetFragDataLocation");
    return 0;
  }

  void APIENTRY glGetFramebufferAttachmentParameteriv(GLenum target, GLenum attachment, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetFramebufferAttachmentParameteriv");
  }

  void APIENTRY glGetMultisamplefv(GLenum pname, GLuint index, GLfloat *val) {
    mithril::GlStubCalled("glGetMultisamplefv");
  }

  void APIENTRY glGetQueryObjecti64v(GLuint id, GLenum pname, GLint64 *params) {
    mithril::GlStubCalled("glGetQueryObjecti64v");
  }

  void APIENTRY glGetQueryObjectiv(GLuint id, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetQueryObjectiv");
  }

  void APIENTRY glGetQueryObjectui64v(GLuint id, GLenum pname, GLuint64 *params) {
    mithril::GlStubCalled("glGetQueryObjectui64v");
  }

  void APIENTRY glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint *params) {
    mithril::GlStubCalled("glGetQueryObjectuiv");
  }

  void APIENTRY glGetQueryiv(GLenum target, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetQueryiv");
  }

  void APIENTRY glGetRenderbufferParameteriv(GLenum target, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetRenderbufferParameteriv");
  }

  void APIENTRY glGetSamplerParameterIiv(GLuint sampler, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetSamplerParameterIiv");
  }

  void APIENTRY glGetSamplerParameterIuiv(GLuint sampler, GLenum pname, GLuint *params) {
    mithril::GlStubCalled("glGetSamplerParameterIuiv");
  }

  void APIENTRY glGetSamplerParameterfv(GLuint sampler, GLenum pname, GLfloat *params) {
    mithril::GlStubCalled("glGetSamplerParameterfv");
  }

  void APIENTRY glGetSamplerParameteriv(GLuint sampler, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetSamplerParameteriv");
  }

  void APIENTRY glGetSynciv(GLsync sync, GLenum pname, GLsizei count, GLsizei *length, GLint *values) {
    mithril::GlStubCalled("glGetSynciv");
  }

  void APIENTRY glGetTexImage(GLenum target, GLint level, GLenum format, GLenum type, void *pixels) {
    mithril::GlStubCalled("glGetTexImage");
  }

  void APIENTRY glGetTexLevelParameterfv(GLenum target, GLint level, GLenum pname, GLfloat *params) {
    mithril::GlStubCalled("glGetTexLevelParameterfv");
  }

  void APIENTRY glGetTexLevelParameteriv(GLenum target, GLint level, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetTexLevelParameteriv");
  }

  void APIENTRY glGetTexParameterIiv(GLenum target, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetTexParameterIiv");
  }

  void APIENTRY glGetTexParameterIuiv(GLenum target, GLenum pname, GLuint *params) {
    mithril::GlStubCalled("glGetTexParameterIuiv");
  }

  void APIENTRY glGetTexParameterfv(GLenum target, GLenum pname, GLfloat *params) {
    mithril::GlStubCalled("glGetTexParameterfv");
  }

  void APIENTRY glGetTexParameteriv(GLenum target, GLenum pname, GLint *params) {
    mithril::GlStubCalled("glGetTexParameteriv");
  }

  void APIENTRY glGetTransformFeedbackVarying(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name) {
    mithril::GlStubCalled("glGetTransformFeedbackVarying");
  }

  GLuint APIENTRY glGetUniformBlockIndex(GLuint program, const GLchar *uniformBlockName) {
    mithril::GlStubCalled("glGetUniformBlockIndex");
    return 0;
  }

  void APIENTRY glGetUniformIndices(GLuint program, GLsizei uniformCount, const GLchar *const*uniformNames, GLuint *uniformIndices) {
    mithril::GlStubCalled("glGetUniformIndices");
  }

  GLboolean APIENTRY glIsFramebuffer(GLuint framebuffer) {
    mithril::GlStubCalled("glIsFramebuffer");
    return 0;
  }

  GLboolean APIENTRY glIsQuery(GLuint id) {
    mithril::GlStubCalled("glIsQuery");
    return 0;
  }

  GLboolean APIENTRY glIsRenderbuffer(GLuint renderbuffer) {
    mithril::GlStubCalled("glIsRenderbuffer");
    return 0;
  }

  GLboolean APIENTRY glIsSampler(GLuint sampler) {
    mithril::GlStubCalled("glIsSampler");
    return 0;
  }

  GLboolean APIENTRY glIsSync(GLsync sync) {
    mithril::GlStubCalled("glIsSync");
    return 0;
  }

  GLboolean APIENTRY glIsTexture(GLuint texture) {
    mithril::GlStubCalled("glIsTexture");
    return 0;
  }

  void APIENTRY glPixelStoref(GLenum pname, GLfloat param) {
    mithril::GlStubCalled("glPixelStoref");
  }

  void APIENTRY glPointParameterf(GLenum pname, GLfloat param) {
    mithril::GlStubCalled("glPointParameterf");
  }

  void APIENTRY glPointParameterfv(GLenum pname, const GLfloat *params) {
    mithril::GlStubCalled("glPointParameterfv");
  }

  void APIENTRY glPointParameteri(GLenum pname, GLint param) {
    mithril::GlStubCalled("glPointParameteri");
  }

  void APIENTRY glPointParameteriv(GLenum pname, const GLint *params) {
    mithril::GlStubCalled("glPointParameteriv");
  }

  void APIENTRY glPrimitiveRestartIndex(GLuint index) {
    mithril::GlStubCalled("glPrimitiveRestartIndex");
  }

  void APIENTRY glProvokingVertex(GLenum mode) {
    mithril::GlStubCalled("glProvokingVertex");
  }

  void APIENTRY glQueryCounter(GLuint id, GLenum target) {
    mithril::GlStubCalled("glQueryCounter");
  }

  void APIENTRY glReadBuffer(GLenum src) {
    mithril::GlStubCalled("glReadBuffer");
  }

  void APIENTRY glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height) {
    mithril::GlStubCalled("glRenderbufferStorage");
  }

  void APIENTRY glRenderbufferStorageMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height) {
    mithril::GlStubCalled("glRenderbufferStorageMultisample");
  }

  void APIENTRY glSamplerParameterIiv(GLuint sampler, GLenum pname, const GLint *param) {
    mithril::GlStubCalled("glSamplerParameterIiv");
  }

  void APIENTRY glSamplerParameterIuiv(GLuint sampler, GLenum pname, const GLuint *param) {
    mithril::GlStubCalled("glSamplerParameterIuiv");
  }

  void APIENTRY glSamplerParameterf(GLuint sampler, GLenum pname, GLfloat param) {
    mithril::GlStubCalled("glSamplerParameterf");
  }

  void APIENTRY glSamplerParameterfv(GLuint sampler, GLenum pname, const GLfloat *param) {
    mithril::GlStubCalled("glSamplerParameterfv");
  }

  void APIENTRY glSamplerParameteri(GLuint sampler, GLenum pname, GLint param) {
    mithril::GlStubCalled("glSamplerParameteri");
  }

  void APIENTRY glSamplerParameteriv(GLuint sampler, GLenum pname, const GLint *param) {
    mithril::GlStubCalled("glSamplerParameteriv");
  }

  void APIENTRY glTexBuffer(GLenum target, GLenum internalformat, GLuint buffer) {
    mithril::GlStubCalled("glTexBuffer");
  }

  void APIENTRY glTexImage1D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const void *pixels) {
    mithril::GlStubCalled("glTexImage1D");
  }

  void APIENTRY glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels) {
    mithril::GlStubCalled("glTexImage2D");
  }

  void APIENTRY glTexImage2DMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations) {
    mithril::GlStubCalled("glTexImage2DMultisample");
  }

  void APIENTRY glTexImage3D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels) {
    mithril::GlStubCalled("glTexImage3D");
  }

  void APIENTRY glTexImage3DMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations) {
    mithril::GlStubCalled("glTexImage3DMultisample");
  }

  void APIENTRY glTexParameterIiv(GLenum target, GLenum pname, const GLint *params) {
    mithril::GlStubCalled("glTexParameterIiv");
  }

  void APIENTRY glTexParameterIuiv(GLenum target, GLenum pname, const GLuint *params) {
    mithril::GlStubCalled("glTexParameterIuiv");
  }

  void APIENTRY glTexParameterf(GLenum target, GLenum pname, GLfloat param) {
    mithril::GlStubCalled("glTexParameterf");
  }

  void APIENTRY glTexParameterfv(GLenum target, GLenum pname, const GLfloat *params) {
    mithril::GlStubCalled("glTexParameterfv");
  }

  void APIENTRY glTexParameteri(GLenum target, GLenum pname, GLint param) {
    mithril::GlStubCalled("glTexParameteri");
  }

  void APIENTRY glTexParameteriv(GLenum target, GLenum pname, const GLint *params) {
    mithril::GlStubCalled("glTexParameteriv");
  }

  void APIENTRY glTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void *pixels) {
    mithril::GlStubCalled("glTexSubImage1D");
  }

  void APIENTRY glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels) {
    mithril::GlStubCalled("glTexSubImage2D");
  }

  void APIENTRY glTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels) {
    mithril::GlStubCalled("glTexSubImage3D");
  }

  void APIENTRY glTransformFeedbackVaryings(GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode) {
    mithril::GlStubCalled("glTransformFeedbackVaryings");
  }

  void APIENTRY glUniformBlockBinding(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding) {
    mithril::GlStubCalled("glUniformBlockBinding");
  }

  void APIENTRY glVertexAttribI1i(GLuint index, GLint x) {
    mithril::GlStubCalled("glVertexAttribI1i");
  }

  void APIENTRY glVertexAttribI1iv(GLuint index, const GLint *v) {
    mithril::GlStubCalled("glVertexAttribI1iv");
  }

  void APIENTRY glVertexAttribI1ui(GLuint index, GLuint x) {
    mithril::GlStubCalled("glVertexAttribI1ui");
  }

  void APIENTRY glVertexAttribI1uiv(GLuint index, const GLuint *v) {
    mithril::GlStubCalled("glVertexAttribI1uiv");
  }

  void APIENTRY glVertexAttribI2i(GLuint index, GLint x, GLint y) {
    mithril::GlStubCalled("glVertexAttribI2i");
  }

  void APIENTRY glVertexAttribI2iv(GLuint index, const GLint *v) {
    mithril::GlStubCalled("glVertexAttribI2iv");
  }

  void APIENTRY glVertexAttribI2ui(GLuint index, GLuint x, GLuint y) {
    mithril::GlStubCalled("glVertexAttribI2ui");
  }

  void APIENTRY glVertexAttribI2uiv(GLuint index, const GLuint *v) {
    mithril::GlStubCalled("glVertexAttribI2uiv");
  }

  void APIENTRY glVertexAttribI3i(GLuint index, GLint x, GLint y, GLint z) {
    mithril::GlStubCalled("glVertexAttribI3i");
  }

  void APIENTRY glVertexAttribI3iv(GLuint index, const GLint *v) {
    mithril::GlStubCalled("glVertexAttribI3iv");
  }

  void APIENTRY glVertexAttribI3ui(GLuint index, GLuint x, GLuint y, GLuint z) {
    mithril::GlStubCalled("glVertexAttribI3ui");
  }

  void APIENTRY glVertexAttribI3uiv(GLuint index, const GLuint *v) {
    mithril::GlStubCalled("glVertexAttribI3uiv");
  }

  void APIENTRY glVertexAttribI4bv(GLuint index, const GLbyte *v) {
    mithril::GlStubCalled("glVertexAttribI4bv");
  }

  void APIENTRY glVertexAttribI4i(GLuint index, GLint x, GLint y, GLint z, GLint w) {
    mithril::GlStubCalled("glVertexAttribI4i");
  }

  void APIENTRY glVertexAttribI4iv(GLuint index, const GLint *v) {
    mithril::GlStubCalled("glVertexAttribI4iv");
  }

  void APIENTRY glVertexAttribI4sv(GLuint index, const GLshort *v) {
    mithril::GlStubCalled("glVertexAttribI4sv");
  }

  void APIENTRY glVertexAttribI4ubv(GLuint index, const GLubyte *v) {
    mithril::GlStubCalled("glVertexAttribI4ubv");
  }

  void APIENTRY glVertexAttribI4ui(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w) {
    mithril::GlStubCalled("glVertexAttribI4ui");
  }

  void APIENTRY glVertexAttribI4uiv(GLuint index, const GLuint *v) {
    mithril::GlStubCalled("glVertexAttribI4uiv");
  }

  void APIENTRY glVertexAttribI4usv(GLuint index, const GLushort *v) {
    mithril::GlStubCalled("glVertexAttribI4usv");
  }

  void APIENTRY glVertexAttribP1ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP1ui");
  }

  void APIENTRY glVertexAttribP1uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP1uiv");
  }

  void APIENTRY glVertexAttribP2ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP2ui");
  }

  void APIENTRY glVertexAttribP2uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP2uiv");
  }

  void APIENTRY glVertexAttribP3ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP3ui");
  }

  void APIENTRY glVertexAttribP3uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP3uiv");
  }

  void APIENTRY glVertexAttribP4ui(GLuint index, GLenum type, GLboolean normalized, GLuint value) {
    mithril::GlStubCalled("glVertexAttribP4ui");
  }

  void APIENTRY glVertexAttribP4uiv(GLuint index, GLenum type, GLboolean normalized, const GLuint *value) {
    mithril::GlStubCalled("glVertexAttribP4uiv");
  }

  void APIENTRY glWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout) {
    mithril::GlStubCalled("glWaitSync");
  }

} // extern "C"
