#!/usr/bin/env python3
"""Regenerate src/gl/gl_exports.cpp (GL 3.3 core stub exports).

Reads docs/gl33_core_list.md for the function set and real prototypes from
third_party/GL/glcorearb.h. Functions listed in MGL_IMPL are implemented for
real in src/gl/gl_impl.cpp and are skipped here.

Run: python3 scripts/gen_gl_stubs.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HDR = ROOT / "third_party" / "GL" / "glcorearb.h"
GL_LIST = ROOT / "docs" / "gl33_core_list.md"
OUT = ROOT / "src" / "gl" / "gl_exports.cpp"

# Functions that have real implementations in src/gl/gl_impl.cpp.
MGL_IMPL = frozenset({
    "glBlendColor", "glBlendEquation", "glBlendEquationSeparate", "glBlendFunc",
    "glBlendFuncSeparate", "glClear", "glClearColor", "glClearDepth", "glClearStencil",
    "glColorMask", "glColorMaski", "glCullFace", "glDepthFunc", "glDepthMask",
    "glDepthRange", "glDisable", "glDisablei", "glEnable", "glEnablei",
    "glFinish", "glFlush", "glFrontFace", "glGetBooleanv", "glGetDoublev",
    "glGetError", "glGetFloatv", "glGetIntegerv", "glGetInteger64v",
    "glGetString", "glGetStringi", "glHint", "glIsEnabled", "glIsEnabledi",
    "glLineWidth", "glLogicOp", "glPixelStorei", "glPointSize", "glPolygonMode",
    "glPolygonOffset", "glSampleCoverage", "glSampleMaski", "glScissor",
    "glStencilFunc", "glStencilFuncSeparate", "glStencilMask",
    "glStencilMaskSeparate", "glStencilOp", "glStencilOpSeparate", "glViewport",
    "glGetPointerv", "glClampColor",
    # S2 shaders/programs/uniforms implemented in gl_impl.cpp.
    "glAttachShader", "glBindAttribLocation", "glCompileShader", "glCreateProgram",
    "glCreateShader", "glDeleteProgram", "glDeleteShader", "glDetachShader",
    "glGetActiveAttrib", "glGetActiveUniform", "glGetAttachedShaders",
    "glGetAttribLocation", "glGetProgramInfoLog", "glGetProgramiv",
    "glGetShaderInfoLog", "glGetShaderSource", "glGetShaderiv",
    "glGetUniformLocation", "glGetUniformfv", "glGetUniformiv", "glGetUniformuiv",
    "glIsProgram", "glIsShader", "glLinkProgram", "glShaderSource",
    "glUniform1f", "glUniform1fv", "glUniform1i", "glUniform1iv", "glUniform1ui",
    "glUniform1uiv", "glUniform2f", "glUniform2fv", "glUniform2i", "glUniform2iv",
    "glUniform2ui", "glUniform2uiv", "glUniform3f", "glUniform3fv", "glUniform3i",
    "glUniform3iv", "glUniform3ui", "glUniform3uiv", "glUniform4f", "glUniform4fv",
    "glUniform4i", "glUniform4iv", "glUniform4ui", "glUniform4uiv",
    "glUniformMatrix2fv", "glUniformMatrix2x3fv", "glUniformMatrix2x4fv",
    "glUniformMatrix3fv", "glUniformMatrix3x2fv", "glUniformMatrix3x4fv",
    "glUniformMatrix4fv", "glUniformMatrix4x2fv", "glUniformMatrix4x3fv",
    "glUseProgram", "glValidateProgram",
})


def parse_list():
    txt = GL_LIST.read_text()
    names = set()
    for line in txt.splitlines():
        line = line.strip()
        if line.startswith("gl"):
            names.update(line.split())
    return sorted(names)


def parse_decls(hdr_text):
    # Every prototype lives in its own ;-terminated unit; strip comments and
    # preprocessor lines first so '#define GLAPI extern' cannot pollute a match.
    hdr = re.sub(r"/\*.*?\*/", " ", hdr_text, flags=re.S)
    hdr = re.sub(r"(?m)^#.*$", "", hdr)
    pat = re.compile(r"\bGLAPI\s+(.*?)\s*APIENTRY\s+(gl[A-Za-z0-9]+)\s*\((.*?)\)\s*$",
                     re.S)
    decls = {}
    for unit in hdr.split(";"):
        m = pat.search(unit)
        if m:
            decls[m.group(2)] = (re.sub(r"\s+", " ", m.group(1)).strip(),
                                 m.group(3).strip())
    return decls


def safe_expr(rtype):
    rt = rtype.rstrip()
    if rt == "void":
        return None
    if rt in ("GLintptr", "GLsizeiptr", "GLsync") or rt.endswith("*"):
        return "nullptr"
    if rt in ("GLfloat", "GLclampf"):
        return "0.0f"
    if rt in ("GLdouble", "GLclampd"):
        return "0.0"
    return "0"


def main():
    wanted = parse_list()
    decls = parse_decls(HDR.read_text())
    missing = set(wanted) - set(decls)
    if missing:
        print("missing prototypes:", sorted(missing))
        sys.exit(1)

    emit = [n for n in wanted if n not in MGL_IMPL]
    lines = [
        "// Mithril-Wrapper GL entry points -- stub table.",
        "// GENERATED by scripts/gen_gl_stubs.py -- DO NOT EDIT BY HAND.",
        "#include <GL/glcorearb.h>",
        "",
        "namespace mithril {",
        "void GlStubCalled(const char* name);",
        "} // namespace mithril",
        "",
        'extern "C" {',
        "",
    ]
    for name in emit:
        rtype, args = decls[name]
        ret = safe_expr(rtype)
        if ret is None:
            lines.append(
                f"  {rtype} APIENTRY {name}({args}) {{\n"
                f'    mithril::GlStubCalled("{name}");\n  }}')
        else:
            lines.append(
                f"  {rtype} APIENTRY {name}({args}) {{\n"
                f'    mithril::GlStubCalled("{name}");\n'
                f"    return {ret};\n  }}")
        lines.append("")
    lines.append('} // extern "C"')
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}: {len(emit)} stubs, "
          f"{len(wanted) - len(emit)} implemented in gl_impl.cpp")


if __name__ == "__main__":
    main()